// Los países de Geografía: de aquí salen sus tres tipos de pregunta (capitales, banderas y ubicación), que
// `npm run geo:upload --prefix backend` sube a la tabla `questions` de Supabase (ver geo/geoQuestions.js).
//
// country(código ISO, nombre en el mapa, nombre, capital, [capital, bandera, ubicación], opciones)
//   - nombre en el mapa: `properties.name` del país en world-atlas/countries-50m.json (null si no está dibujado).
//   - niveles: 1 fácil, 2 media, 3 difícil, 0 = no se pregunta (Israel sin capital por disputada; las banderas de
//     Chad y Mónaco son casi iguales a las de Rumanía e Indonesia; Tuvalu no está en el mapa).
//   - opciones: aliases (otros nombres del país, para las banderas), capitalAliases (otras capitales válidas o
//     grafías), of ("del Reino Unido" en vez de "de Reino Unido"), label (nombre visible si hace falta aclararlo) y
//     extraMap (otras zonas del mapa que cuentan como el país).
//   Los nombres parecidos de otros países ("Níger" / "Nigeria") se rechazan solos: ver rejectLookAlikes.

function country(code, map, name, capital, levels, options = {}) {
  const label = options.label || name;
  return {
    code,
    name,
    label,
    of: options.of || `de ${label}`,
    capital,
    capitalAliases: options.capitalAliases || [],
    aliases: options.aliases || [],
    map: map ? [map, ...(options.extraMap || [])] : [],
    levels: { capital: capital ? levels[0] : 0, flag: levels[1], location: map ? levels[2] : 0 },
  };
}

export const COUNTRIES = [
  // Europa
  country("AL", "Albania", "Albania", "Tirana", [2, 2, 2]),
  country("AD", "Andorra", "Andorra", "Andorra la Vieja", [2, 3, 3], { capitalAliases: ["Andorra la Vella"] }),
  country("AT", "Austria", "Austria", "Viena", [1, 2, 2], { capitalAliases: ["Vienna", "Wien"] }),
  country("BY", "Belarus", "Bielorrusia", "Minsk", [2, 3, 2], { aliases: ["Belarús"] }),
  country("BE", "Belgium", "Bélgica", "Bruselas", [1, 2, 2], { capitalAliases: ["Brussels", "Bruxelles"] }),
  country("BA", "Bosnia and Herz.", "Bosnia y Herzegovina", "Sarajevo", [2, 3, 3], { aliases: ["Bosnia", "Bosnia Herzegovina"] }),
  country("BG", "Bulgaria", "Bulgaria", "Sofía", [2, 3, 2]),
  country("HR", "Croatia", "Croacia", "Zagreb", [2, 2, 2]),
  country("CY", "Cyprus", "Chipre", "Nicosia", [2, 3, 2], { extraMap: ["N. Cyprus"] }),
  country("CZ", "Czechia", "Chequia", "Praga", [1, 2, 2], { aliases: ["República Checa"], capitalAliases: ["Prague", "Praha"] }),
  country("DK", "Denmark", "Dinamarca", "Copenhague", [2, 2, 2], { capitalAliases: ["Copenhagen", "Kobenhavn"] }),
  country("EE", "Estonia", "Estonia", "Tallin", [3, 3, 2], { capitalAliases: ["Tallinn"] }),
  country("FI", "Finland", "Finlandia", "Helsinki", [2, 2, 2]),
  country("FR", "France", "Francia", "París", [1, 1, 1]),
  country("DE", "Germany", "Alemania", "Berlín", [1, 1, 1]),
  country("GR", "Greece", "Grecia", "Atenas", [1, 2, 1]),
  country("HU", "Hungary", "Hungría", "Budapest", [2, 2, 2]),
  country("IS", "Iceland", "Islandia", "Reikiavik", [2, 2, 1], { capitalAliases: ["Reykjavik"] }),
  country("IE", "Ireland", "Irlanda", "Dublín", [1, 2, 1]),
  country("IT", "Italy", "Italia", "Roma", [1, 1, 1]),
  country("LV", "Latvia", "Letonia", "Riga", [3, 3, 2]),
  country("LI", "Liechtenstein", "Liechtenstein", "Vaduz", [3, 3, 3]),
  country("LT", "Lithuania", "Lituania", "Vilna", [3, 3, 2], { capitalAliases: ["Vilnius"] }),
  country("LU", "Luxembourg", "Luxemburgo", "Luxemburgo", [2, 3, 3], { capitalAliases: ["Ciudad de Luxemburgo"] }),
  country("MT", "Malta", "Malta", "La Valeta", [3, 3, 3], { capitalAliases: ["Valletta"] }),
  country("MD", "Moldova", "Moldavia", "Chisináu", [3, 3, 3], { aliases: ["Moldova"], capitalAliases: ["Kishinev"] }),
  country("MC", "Monaco", "Mónaco", "Mónaco", [2, 0, 3]),
  country("ME", "Montenegro", "Montenegro", "Podgorica", [3, 3, 3]),
  country("NL", "Netherlands", "Países Bajos", "Ámsterdam", [1, 2, 2], { aliases: ["Holanda"], of: "de los Países Bajos" }),
  country("MK", "Macedonia", "Macedonia del Norte", "Skopie", [3, 3, 3], { aliases: ["Macedonia"], capitalAliases: ["Skopje"] }),
  country("NO", "Norway", "Noruega", "Oslo", [1, 2, 1]),
  country("PL", "Poland", "Polonia", "Varsovia", [2, 2, 2], { capitalAliases: ["Warsaw", "Warszawa"] }),
  country("PT", "Portugal", "Portugal", "Lisboa", [1, 1, 1]),
  country("RO", "Romania", "Rumanía", "Bucarest", [2, 2, 2]),
  country("RU", "Russia", "Rusia", "Moscú", [1, 1, 1], { aliases: ["Federación Rusa"] }),
  country("SM", "San Marino", "San Marino", "San Marino", [2, 3, 3], { capitalAliases: ["Ciudad de San Marino"] }),
  country("RS", "Serbia", "Serbia", "Belgrado", [2, 3, 2], { capitalAliases: ["Beograd"] }),
  country("SK", "Slovakia", "Eslovaquia", "Bratislava", [2, 3, 2]),
  country("SI", "Slovenia", "Eslovenia", "Liubliana", [3, 3, 2], { capitalAliases: ["Ljubljana"] }),
  country("ES", "Spain", "España", "Madrid", [1, 1, 1]),
  country("SE", "Sweden", "Suecia", "Estocolmo", [2, 1, 1], { capitalAliases: ["Stockholm"] }),
  country("CH", "Switzerland", "Suiza", "Berna", [2, 1, 2], { capitalAliases: ["Bern", "Berne"] }),
  country("UA", "Ukraine", "Ucrania", "Kiev", [1, 2, 1], { capitalAliases: ["Kyiv"] }),
  country("GB", "United Kingdom", "Reino Unido", "Londres", [1, 1, 1], {
    aliases: ["Gran Bretaña", "UK"],
    of: "del Reino Unido",
    capitalAliases: ["London"],
  }),
  country("VA", "Vatican", "Ciudad del Vaticano", "Ciudad del Vaticano", [2, 2, 3], {
    aliases: ["Vaticano", "Santa Sede"],
    of: "del Vaticano",
    capitalAliases: ["Vaticano"],
  }),
  country("GE", "Georgia", "Georgia", "Tiflis", [3, 3, 2], { capitalAliases: ["Tbilisi"] }),
  country("AM", "Armenia", "Armenia", "Ereván", [3, 3, 3], { capitalAliases: ["Yerevan", "Erevan"] }),
  country("AZ", "Azerbaijan", "Azerbaiyán", "Bakú", [3, 3, 3], { aliases: ["Azerbaijan"] }),
  country("TR", "Turkey", "Turquía", "Ankara", [2, 1, 1], { aliases: ["Türkiye"] }),
  country("KZ", "Kazakhstan", "Kazajistán", "Astaná", [3, 3, 2], { aliases: ["Kazajstán", "Kazakhstan"], capitalAliases: ["Nur Sultán"] }),

  // Asia
  country("AF", "Afghanistan", "Afganistán", "Kabul", [2, 3, 2]),
  country("BH", "Bahrain", "Baréin", "Manama", [3, 3, 3], { aliases: ["Bahréin", "Bahrain"] }),
  country("BD", "Bangladesh", "Bangladés", "Daca", [3, 2, 2], { aliases: ["Bangladesh"], capitalAliases: ["Dhaka", "Dacca"] }),
  country("BT", "Bhutan", "Bután", "Timbu", [3, 3, 3], { capitalAliases: ["Thimphu", "Timpu"] }),
  country("BN", "Brunei", "Brunéi", "Bandar Seri Begawan", [3, 3, 3]),
  country("KH", "Cambodia", "Camboya", "Nom Pen", [3, 3, 2], { capitalAliases: ["Phnom Penh"] }),
  country("CN", "China", "China", "Pekín", [1, 1, 1], { capitalAliases: ["Beijing"] }),
  country("IN", "India", "India", "Nueva Delhi", [1, 1, 1], { capitalAliases: ["Delhi", "New Delhi"] }),
  country("ID", "Indonesia", "Indonesia", "Yakarta", [2, 2, 1], { capitalAliases: ["Jakarta", "Nusantara"] }),
  country("IR", "Iran", "Irán", "Teherán", [2, 2, 2], { capitalAliases: ["Tehran"] }),
  country("IQ", "Iraq", "Irak", "Bagdad", [2, 2, 2], { aliases: ["Iraq"] }),
  country("IL", "Israel", "Israel", null, [0, 1, 2]),
  country("JP", "Japan", "Japón", "Tokio", [1, 1, 1], { capitalAliases: ["Tokyo"] }),
  country("JO", "Jordan", "Jordania", "Amán", [3, 3, 2], { capitalAliases: ["Amman"] }),
  country("KW", "Kuwait", "Kuwait", "Kuwait", [2, 3, 3], { capitalAliases: ["Ciudad de Kuwait"] }),
  country("KG", "Kyrgyzstan", "Kirguistán", "Biskek", [3, 3, 3], { aliases: ["Kirguizistán", "Kirguizia"], capitalAliases: ["Bishkek"] }),
  country("LA", "Laos", "Laos", "Vientián", [3, 3, 2], { capitalAliases: ["Vientiane"] }),
  country("LB", "Lebanon", "Líbano", "Beirut", [2, 2, 2]),
  country("MY", "Malaysia", "Malasia", "Kuala Lumpur", [2, 3, 2], { capitalAliases: ["Putrajaya"] }),
  country("MV", "Maldives", "Maldivas", "Malé", [3, 3, 3], { of: "de las Maldivas" }),
  country("MN", "Mongolia", "Mongolia", "Ulán Bator", [2, 3, 2], { capitalAliases: ["Ulaanbaatar"] }),
  country("MM", "Myanmar", "Myanmar", "Naipyidó", [3, 3, 2], { aliases: ["Birmania"], capitalAliases: ["Naypyidaw", "Nay Pyi Taw"] }),
  country("NP", "Nepal", "Nepal", "Katmandú", [2, 2, 2], { capitalAliases: ["Kathmandu"] }),
  country("KP", "North Korea", "Corea del Norte", "Pionyang", [2, 2, 2], { capitalAliases: ["Pyongyang"] }),
  country("OM", "Oman", "Omán", "Mascate", [3, 3, 3], { capitalAliases: ["Muscat"] }),
  country("PK", "Pakistan", "Pakistán", "Islamabad", [2, 2, 2]),
  country("PH", "Philippines", "Filipinas", "Manila", [2, 2, 2]),
  country("QA", "Qatar", "Catar", "Doha", [2, 3, 3], { aliases: ["Qatar"] }),
  country("SA", "Saudi Arabia", "Arabia Saudita", "Riad", [2, 2, 1], { aliases: ["Arabia Saudí", "Arabia"], capitalAliases: ["Riyadh"] }),
  country("SG", "Singapore", "Singapur", "Singapur", [2, 3, 3], { aliases: ["Singapore"], capitalAliases: ["Singapore"] }),
  country("KR", "South Korea", "Corea del Sur", "Seúl", [1, 1, 2], { capitalAliases: ["Seoul"] }),
  country("LK", "Sri Lanka", "Sri Lanka", "Sri Jayawardenapura Kotte", [3, 3, 2], {
    capitalAliases: ["Kotte", "Sri Jayawardenepura Kotte", "Colombo"],
  }),
  country("SY", "Syria", "Siria", "Damasco", [2, 3, 2], { capitalAliases: ["Damascus"] }),
  country("TJ", "Tajikistan", "Tayikistán", "Dusambé", [3, 3, 3], { aliases: ["Tadjikistán", "Tajikistan"], capitalAliases: ["Dushanbe"] }),
  country("TH", "Thailand", "Tailandia", "Bangkok", [1, 2, 2]),
  country("TL", "Timor-Leste", "Timor Oriental", "Dili", [3, 3, 3], { aliases: ["Timor Leste", "Timor"] }),
  country("TM", "Turkmenistan", "Turkmenistán", "Asjabad", [3, 3, 3], { capitalAliases: ["Ashgabat", "Asgabat"] }),
  country("AE", "United Arab Emirates", "Emiratos Árabes Unidos", "Abu Dabi", [2, 2, 2], {
    aliases: ["Emiratos Árabes", "Emiratos", "EAU"],
    of: "de los Emiratos Árabes Unidos",
    capitalAliases: ["Abu Dhabi"],
  }),
  country("UZ", "Uzbekistan", "Uzbekistán", "Taskent", [3, 3, 3], { capitalAliases: ["Tashkent"] }),
  country("VN", "Vietnam", "Vietnam", "Hanói", [2, 1, 2]),
  country("YE", "Yemen", "Yemen", "Saná", [3, 3, 2], { capitalAliases: ["Sanaa"] }),

  // África
  country("DZ", "Algeria", "Argelia", "Argel", [2, 2, 2], { capitalAliases: ["Algiers"] }),
  country("AO", "Angola", "Angola", "Luanda", [2, 3, 2]),
  country("BJ", "Benin", "Benín", "Porto Novo", [3, 3, 3], { capitalAliases: ["Cotonú", "Cotonou"] }),
  country("BW", "Botswana", "Botsuana", "Gaborone", [3, 3, 3], { aliases: ["Botswana"] }),
  country("BF", "Burkina Faso", "Burkina Faso", "Uagadugú", [3, 3, 3], { aliases: ["Burkina"], capitalAliases: ["Ouagadougou"] }),
  country("BI", "Burundi", "Burundi", "Gitega", [3, 3, 3], { capitalAliases: ["Buyumbura", "Bujumbura"] }),
  country("CV", "Cabo Verde", "Cabo Verde", "Praia", [3, 3, 3], { aliases: ["Cape Verde"] }),
  country("CM", "Cameroon", "Camerún", "Yaundé", [3, 3, 2], { capitalAliases: ["Yaounde"] }),
  country("CF", "Central African Rep.", "República Centroafricana", "Bangui", [3, 3, 3], {
    aliases: ["Centroáfrica", "RCA"],
    of: "de la República Centroafricana",
  }),
  country("TD", "Chad", "Chad", "Yamena", [3, 0, 2], { capitalAliases: ["N'Djamena", "Ndjamena"] }),
  country("KM", "Comoros", "Comoras", "Moroni", [3, 3, 3], { aliases: ["Comores"], of: "de las Comoras" }),
  country("CG", "Congo", "República del Congo", "Brazzaville", [3, 3, 3], {
    aliases: ["Congo", "Congo Brazzaville"],
    of: "de la República del Congo",
  }),
  country("CD", "Dem. Rep. Congo", "República Democrática del Congo", "Kinsasa", [2, 3, 2], {
    aliases: ["RD Congo", "RDC", "Congo Kinsasa", "Congo Kinshasa", "Zaire"],
    of: "de la República Democrática del Congo",
    capitalAliases: ["Kinshasa"],
  }),
  country("CI", "Côte d'Ivoire", "Costa de Marfil", "Yamusukro", [3, 2, 3], {
    aliases: ["Côte d'Ivoire"],
    capitalAliases: ["Yamoussoukro", "Abiyán", "Abidjan"],
  }),
  country("DJ", "Djibouti", "Yibuti", "Yibuti", [3, 3, 3], { aliases: ["Djibouti"], capitalAliases: ["Djibouti"] }),
  country("EG", "Egypt", "Egipto", "El Cairo", [1, 2, 1]),
  country("GQ", "Eq. Guinea", "Guinea Ecuatorial", "Malabo", [2, 3, 3]),
  country("ER", "Eritrea", "Eritrea", "Asmara", [3, 3, 3]),
  country("SZ", "eSwatini", "Esuatini", "Mbabane", [3, 3, 3], { aliases: ["Suazilandia", "Eswatini"], capitalAliases: ["Lobamba"] }),
  country("ET", "Ethiopia", "Etiopía", "Adís Abeba", [2, 3, 2], { capitalAliases: ["Addis Ababa"] }),
  country("GA", "Gabon", "Gabón", "Libreville", [3, 3, 3]),
  country("GM", "Gambia", "Gambia", "Banjul", [3, 3, 3]),
  country("GH", "Ghana", "Ghana", "Acra", [3, 3, 2], { capitalAliases: ["Accra"] }),
  country("GN", "Guinea", "Guinea", "Conakri", [3, 3, 3], { capitalAliases: ["Conakry"] }),
  country("GW", "Guinea-Bissau", "Guinea-Bisáu", "Bisáu", [3, 3, 3], { aliases: ["Guinea Bissau"], capitalAliases: ["Bissau"] }),
  country("KE", "Kenya", "Kenia", "Nairobi", [2, 2, 2], { aliases: ["Kenya"] }),
  country("LS", "Lesotho", "Lesoto", "Maseru", [3, 3, 3], { aliases: ["Lesotho"] }),
  country("LR", "Liberia", "Liberia", "Monrovia", [3, 3, 3]),
  country("LY", "Libya", "Libia", "Trípoli", [2, 3, 2]),
  country("MG", "Madagascar", "Madagascar", "Antananarivo", [2, 3, 1]),
  country("MW", "Malawi", "Malaui", "Lilongüe", [3, 3, 3], { aliases: ["Malawi"], capitalAliases: ["Lilongwe"] }),
  country("ML", "Mali", "Malí", "Bamako", [3, 3, 2]),
  country("MR", "Mauritania", "Mauritania", "Nuakchot", [3, 3, 2], { capitalAliases: ["Nouakchott"] }),
  country("MU", "Mauritius", "Mauricio", "Port Louis", [3, 3, 3], { aliases: ["Isla Mauricio"], capitalAliases: ["Puerto Luis"] }),
  country("MA", "Morocco", "Marruecos", "Rabat", [2, 2, 1]),
  country("MZ", "Mozambique", "Mozambique", "Maputo", [3, 3, 2]),
  country("NA", "Namibia", "Namibia", "Windhoek", [3, 3, 2], { capitalAliases: ["Windhuk"] }),
  country("NE", "Niger", "Níger", "Niamey", [3, 3, 2]),
  country("NG", "Nigeria", "Nigeria", "Abuya", [3, 2, 2], { capitalAliases: ["Abuja"] }),
  country("RW", "Rwanda", "Ruanda", "Kigali", [3, 3, 3], { aliases: ["Rwanda"] }),
  country("ST", "São Tomé and Principe", "Santo Tomé y Príncipe", "Santo Tomé", [3, 3, 3], {
    aliases: ["Santo Tomé", "Sao Tomé y Príncipe"],
    capitalAliases: ["Sao Tomé"],
  }),
  country("SN", "Senegal", "Senegal", "Dakar", [2, 3, 2]),
  country("SC", "Seychelles", "Seychelles", "Victoria", [3, 3, 3]),
  country("SL", "Sierra Leone", "Sierra Leona", "Freetown", [3, 3, 3]),
  country("SO", "Somalia", "Somalia", "Mogadiscio", [3, 3, 2], { extraMap: ["Somaliland"], capitalAliases: ["Mogadishu"] }),
  country("ZA", "South Africa", "Sudáfrica", "Pretoria", [2, 2, 1], { capitalAliases: ["Ciudad del Cabo", "Bloemfontein"] }),
  country("SS", "S. Sudan", "Sudán del Sur", "Yuba", [3, 3, 3], { aliases: ["Sur Sudán"], capitalAliases: ["Juba"] }),
  country("SD", "Sudan", "Sudán", "Jartum", [3, 3, 2], { capitalAliases: ["Khartoum"] }),
  country("TZ", "Tanzania", "Tanzania", "Dodoma", [3, 3, 2], { capitalAliases: ["Dar es Salaam"] }),
  country("TG", "Togo", "Togo", "Lomé", [3, 3, 3]),
  country("TN", "Tunisia", "Túnez", "Túnez", [2, 2, 2], { capitalAliases: ["Tunis"] }),
  country("UG", "Uganda", "Uganda", "Kampala", [3, 3, 3]),
  country("ZM", "Zambia", "Zambia", "Lusaka", [3, 3, 3]),
  country("ZW", "Zimbabwe", "Zimbabue", "Harare", [3, 3, 3], { aliases: ["Zimbabwe"] }),

  // América
  country("AG", "Antigua and Barb.", "Antigua y Barbuda", "Saint John's", [3, 3, 3], { aliases: ["Antigua"], capitalAliases: ["San Juan"] }),
  country("AR", "Argentina", "Argentina", "Buenos Aires", [1, 1, 1]),
  country("BS", "Bahamas", "Bahamas", "Nasáu", [3, 3, 2], { of: "de las Bahamas", capitalAliases: ["Nassau"] }),
  country("BB", "Barbados", "Barbados", "Bridgetown", [3, 3, 3]),
  country("BZ", "Belize", "Belice", "Belmopán", [3, 3, 2], { aliases: ["Belize"] }),
  country("BO", "Bolivia", "Bolivia", "Sucre", [1, 2, 1], { capitalAliases: ["La Paz"] }),
  country("BR", "Brazil", "Brasil", "Brasilia", [2, 1, 1]),
  country("CA", "Canada", "Canadá", "Ottawa", [2, 1, 1]),
  country("CL", "Chile", "Chile", "Santiago", [1, 1, 1], { capitalAliases: ["Santiago de Chile"] }),
  country("CO", "Colombia", "Colombia", "Bogotá", [1, 1, 1]),
  country("CR", "Costa Rica", "Costa Rica", "San José", [1, 2, 2]),
  country("CU", "Cuba", "Cuba", "La Habana", [1, 1, 1]),
  country("DM", "Dominica", "Dominica", "Roseau", [3, 3, 3]),
  country("DO", "Dominican Rep.", "República Dominicana", "Santo Domingo", [1, 2, 2], {
    aliases: ["Dominicana"],
    of: "de la República Dominicana",
  }),
  country("EC", "Ecuador", "Ecuador", "Quito", [1, 2, 1]),
  country("SV", "El Salvador", "El Salvador", "San Salvador", [1, 2, 2]),
  country("GD", "Grenada", "Granada", "Saint George's", [3, 3, 3], {
    aliases: ["Grenada"],
    label: "Granada (Caribe)",
    capitalAliases: ["San Jorge"],
  }),
  country("GT", "Guatemala", "Guatemala", "Ciudad de Guatemala", [1, 2, 2], { capitalAliases: ["Guatemala"] }),
  country("GY", "Guyana", "Guyana", "Georgetown", [3, 3, 2], { aliases: ["Guayana"] }),
  country("HT", "Haiti", "Haití", "Puerto Príncipe", [2, 3, 2], { capitalAliases: ["Port-au-Prince"] }),
  country("HN", "Honduras", "Honduras", "Tegucigalpa", [2, 2, 2]),
  country("JM", "Jamaica", "Jamaica", "Kingston", [2, 1, 2]),
  country("MX", "Mexico", "México", "Ciudad de México", [1, 1, 1], { capitalAliases: ["CDMX", "México DF", "DF", "México"] }),
  country("NI", "Nicaragua", "Nicaragua", "Managua", [1, 2, 2]),
  country("PA", "Panama", "Panamá", "Panamá", [1, 2, 1], { capitalAliases: ["Ciudad de Panamá"] }),
  country("PY", "Paraguay", "Paraguay", "Asunción", [1, 2, 1]),
  country("PE", "Peru", "Perú", "Lima", [1, 1, 1]),
  country("KN", "St. Kitts and Nevis", "San Cristóbal y Nieves", "Basseterre", [3, 3, 3], {
    aliases: ["Saint Kitts y Nevis", "San Cristóbal"],
  }),
  country("LC", "Saint Lucia", "Santa Lucía", "Castries", [3, 3, 3], { aliases: ["Saint Lucia"] }),
  country("VC", "St. Vin. and Gren.", "San Vicente y las Granadinas", "Kingstown", [3, 3, 3], { aliases: ["San Vicente"] }),
  country("SR", "Suriname", "Surinam", "Paramaribo", [3, 3, 2], { aliases: ["Suriname"] }),
  country("TT", "Trinidad and Tobago", "Trinidad y Tobago", "Puerto España", [3, 3, 3], {
    aliases: ["Trinidad"],
    capitalAliases: ["Port of Spain"],
  }),
  country("US", "United States of America", "Estados Unidos", "Washington D. C.", [1, 1, 1], {
    aliases: ["EEUU", "EE UU", "USA", "Estados Unidos de América"],
    capitalAliases: ["Washington"],
  }),
  country("UY", "Uruguay", "Uruguay", "Montevideo", [1, 1, 1]),
  country("VE", "Venezuela", "Venezuela", "Caracas", [1, 1, 1]),

  // Oceanía
  country("AU", "Australia", "Australia", "Canberra", [2, 1, 1]),
  country("FJ", "Fiji", "Fiyi", "Suva", [3, 3, 3], { aliases: ["Fiji"] }),
  country("KI", "Kiribati", "Kiribati", "Tarawa", [3, 3, 3], { capitalAliases: ["Tarawa Sur", "South Tarawa"] }),
  country("MH", "Marshall Is.", "Islas Marshall", "Majuro", [3, 3, 3], { aliases: ["Marshall"], of: "de las Islas Marshall" }),
  country("FM", "Micronesia", "Micronesia", "Palikir", [3, 3, 3], { aliases: ["Estados Federados de Micronesia"] }),
  country("NR", "Nauru", "Nauru", "Yaren", [3, 3, 3]),
  country("NZ", "New Zealand", "Nueva Zelanda", "Wellington", [2, 2, 1], { aliases: ["Nueva Zelandia"] }),
  country("PW", "Palau", "Palaos", "Ngerulmud", [3, 3, 3], { aliases: ["Palau"] }),
  country("PG", "Papua New Guinea", "Papúa Nueva Guinea", "Port Moresby", [3, 3, 2], { aliases: ["Papúa"] }),
  country("WS", "Samoa", "Samoa", "Apia", [3, 3, 3]),
  country("SB", "Solomon Is.", "Islas Salomón", "Honiara", [3, 3, 3], { aliases: ["Salomón"], of: "de las Islas Salomón" }),
  country("TO", "Tonga", "Tonga", "Nukualofa", [3, 3, 3], { capitalAliases: ["Nuku'alofa"] }),
  country("TV", null, "Tuvalu", "Funafuti", [3, 3, 0]),
  country("VU", "Vanuatu", "Vanuatu", "Port Vila", [3, 3, 3]),
];
