// Campo de minas · Arte. [difficulty, prompt, right answers, mines] (see ./index.js).
export default [
  // ---- Fácil ----
  [1, "Pintores",
    ["Picasso", "Van Gogh", "Dalí", "Velázquez", "Goya", "Monet", "Rembrandt", "Frida Kahlo", "Miró", "Leonardo da Vinci", "Botticelli", "Renoir", "Cézanne", "Matisse", "El Greco"],
    ["Mozart", "Beethoven", "Cervantes", "Shakespeare", "Einstein", "Napoleón", "Chopin", "Darwin", "Newton", "Neruda"]],
  [1, "Colores",
    ["Rojo", "Azul", "Amarillo", "Verde", "Naranja", "Violeta", "Rosa", "Marrón", "Turquesa", "Cian", "Magenta", "Granate", "Ocre", "Añil", "Lila"],
    ["Cuadrado", "Círculo", "Triángulo", "Pincel", "Lienzo", "Caballete", "Paleta", "Óleo", "Acuarela", "Marco"]],
  [1, "Monumentos de París",
    ["Torre Eiffel", "Arco del Triunfo", "Notre Dame", "Louvre", "Sacré-Cœur", "Panteón", "Los Inválidos", "Ópera Garnier", "Centro Pompidou", "Sainte-Chapelle", "Moulin Rouge", "Torre Montparnasse", "Plaza de la Concordia", "Museo de Orsay", "Jardines de Luxemburgo"],
    ["Big Ben", "Coliseo", "Sagrada Familia", "Puerta de Brandeburgo", "Torre de Pisa", "Estatua de la Libertad", "Partenón", "Palacio de Buckingham", "Puerta de Alcalá", "Fontana de Trevi"]],
  [1, "Museos de arte",
    ["Louvre", "Prado", "MoMA", "Reina Sofía", "Uffizi", "Hermitage", "Thyssen", "Guggenheim", "Rijksmuseum", "Museo de Orsay", "Tate Modern", "National Gallery", "Metropolitan", "Museo Picasso", "Museo Van Gogh"],
    ["Wembley", "Maracaná", "Camp Nou", "Santiago Bernabéu", "Broadway", "Hollywood", "Silicon Valley", "Wall Street", "Times Square", "Las Vegas"]],
  [1, "Cosas que usa un pintor",
    ["Pincel", "Lienzo", "Caballete", "Paleta", "Espátula", "Óleo", "Acuarela", "Acrílico", "Carboncillo", "Trementina", "Témpera", "Gouache", "Bastidor", "Pastel", "Aguarrás"],
    ["Cincel", "Torno de alfarero", "Soplete", "Yunque", "Fragua", "Telar", "Partitura", "Batuta", "Micrófono", "Metrónomo"]],
  [1, "Movimientos artísticos",
    ["Impresionismo", "Cubismo", "Surrealismo", "Barroco", "Renacimiento", "Romanticismo", "Expresionismo", "Gótico", "Románico", "Pop art", "Realismo", "Dadaísmo", "Futurismo", "Neoclasicismo", "Modernismo"],
    ["Feudalismo", "Capitalismo", "Comunismo", "Absolutismo", "Mercantilismo", "Liberalismo", "Budismo", "Hinduismo", "Platonismo", "Darwinismo"]],
  [1, "Pintores españoles",
    ["Velázquez", "Goya", "Picasso", "Dalí", "Miró", "Sorolla", "Murillo", "Zurbarán", "Juan Gris", "José de Ribera", "Antonio López", "Tàpies", "Zuloaga", "Romero de Torres", "María Blanchard"],
    ["Van Gogh", "Monet", "Rembrandt", "Frida Kahlo", "Diego Rivera", "Botero", "Rubens", "Tiziano", "Caravaggio", "Matisse"]],
  [1, "Monumentos de Roma",
    ["Coliseo", "Panteón", "Foro Romano", "Fontana de Trevi", "Castillo de Sant'Angelo", "Plaza Navona", "Escalinata de la Plaza de España", "Arco de Constantino", "Termas de Caracalla", "Circo Máximo", "Vittoriano", "Boca de la Verdad", "Plaza del Popolo", "Columna de Trajano", "Palacio Farnesio"],
    ["Torre de Pisa", "Puente de Rialto", "Duomo de Florencia", "Torre Eiffel", "Big Ben", "Partenón", "Alhambra", "Sagrada Familia", "Puerta de Brandeburgo", "Galería Vittorio Emanuele"]],
  [1, "Técnicas artísticas",
    ["Óleo", "Acuarela", "Fresco", "Grabado", "Mosaico", "Collage", "Temple", "Acrílico", "Carboncillo", "Pastel", "Litografía", "Serigrafía", "Aguafuerte", "Encáustica", "Esgrafiado"],
    ["Soneto", "Sinfonía", "Haiku", "Tango", "Ensayo", "Ópera", "Fábula", "Rap", "Novela", "Vals"]],
  [1, "Monumentos de España",
    ["Sagrada Familia", "Alhambra", "Mezquita de Córdoba", "Acueducto de Segovia", "Catedral de Santiago", "Guggenheim Bilbao", "El Escorial", "Palacio Real de Madrid", "Giralda", "Park Güell", "Ciudad de las Artes y las Ciencias", "Catedral de Burgos", "Alcázar de Segovia", "Teatro romano de Mérida", "Puerta de Alcalá"],
    ["Torre Eiffel", "Coliseo", "Big Ben", "Partenón", "Taj Mahal", "Torre de Pisa", "Kremlin", "Puerta de Brandeburgo", "Estatua de la Libertad", "Ópera de Sídney"]],

  // ---- Media ----
  [2, "Obras de Leonardo da Vinci",
    ["La Gioconda", "La última cena", "El hombre de Vitruvio", "La dama del armiño", "La Virgen de las rocas", "La Anunciación", "San Juan Bautista", "Santa Ana, la Virgen y el Niño", "Ginevra de' Benci", "La adoración de los Magos", "San Jerónimo"],
    ["La noche estrellada", "El grito", "Las meninas", "La creación de Adán", "El nacimiento de Venus", "La joven de la perla", "Guernica", "El beso", "La escuela de Atenas", "El jardín de las delicias", "La persistencia de la memoria", "La primavera", "La ronda de noche", "Los girasoles"]],
  [2, "Escultores",
    ["Miguel Ángel", "Rodin", "Bernini", "Donatello", "Fidias", "Praxíteles", "Canova", "Giacometti", "Henry Moore", "Eduardo Chillida", "Camille Claudel", "Brancusi", "Botero", "Jorge Oteiza", "Louise Bourgeois"],
    ["Van Gogh", "Monet", "Velázquez", "Frida Kahlo", "Goya", "Rembrandt", "Vermeer", "Klimt", "Botticelli", "Caravaggio"]],
  [2, "Obras de Antoni Gaudí",
    ["Sagrada Familia", "Park Güell", "Casa Batlló", "La Pedrera", "Casa Vicens", "Palacio Güell", "El Capricho de Comillas", "Casa Botines", "Palacio Episcopal de Astorga", "Colegio Teresiano", "Cripta de la Colonia Güell", "Torre Bellesguard", "Pabellones Güell"],
    ["Torre Eiffel", "Guggenheim Bilbao", "Casa de las Conchas", "Palau de la Música", "Casa Amatller", "Alhambra", "El Escorial", "Torres Kio", "Ciudad de las Artes y las Ciencias", "Casa Lleó Morera", "Hospital de Sant Pau", "Edificio Metrópolis"]],
  [2, "Cuadros de Van Gogh",
    ["Los girasoles", "La noche estrellada", "Los comedores de patatas", "El dormitorio en Arlés", "Terraza de café por la noche", "Los lirios", "Autorretrato con la oreja vendada", "Campo de trigo con cuervos", "Noche estrellada sobre el Ródano", "El café de noche", "La casa amarilla", "Almendro en flor", "Retrato del doctor Gachet", "La iglesia de Auvers", "La silla de Van Gogh"],
    ["El grito", "Las meninas", "La Gioconda", "Guernica", "El beso", "Impresión, sol naciente", "La joven de la perla", "Los nenúfares", "El nacimiento de Venus", "La persistencia de la memoria"]],
  [2, "Pintores impresionistas",
    ["Monet", "Renoir", "Degas", "Pissarro", "Sisley", "Berthe Morisot", "Mary Cassatt", "Caillebotte", "Bazille", "Guillaumin"],
    ["Picasso", "Dalí", "Velázquez", "Rembrandt", "Miguel Ángel", "Warhol", "Kandinsky", "Mondrian", "Pollock", "Magritte", "Caravaggio", "Rubens", "Frida Kahlo", "Goya", "El Bosco"]],
  [2, "Cuadros de Velázquez",
    ["Las meninas", "La rendición de Breda", "Las hilanderas", "La Venus del espejo", "El aguador de Sevilla", "La fragua de Vulcano", "Retrato de Inocencio X", "Cristo crucificado", "Vieja friendo huevos", "Los borrachos", "El conde-duque de Olivares a caballo", "Felipe IV a caballo", "Baltasar Carlos a caballo", "Juan de Pareja", "La coronación de la Virgen"],
    ["La maja desnuda", "El 3 de mayo", "Saturno devorando a su hijo", "La familia de Carlos IV", "El entierro del conde de Orgaz", "Guernica", "El jardín de las delicias", "El caballero de la mano en el pecho", "La Inmaculada de Soult", "Niños comiendo uvas y melón"]],
  [2, "Cuadros de Goya",
    ["La maja desnuda", "La maja vestida", "El 3 de mayo", "El 2 de mayo", "Saturno devorando a su hijo", "La familia de Carlos IV", "El quitasol", "La gallina ciega", "El perro semihundido", "Duelo a garrotazos", "El aquelarre", "La lechera de Burdeos", "El pelele", "El sueño de la razón produce monstruos", "La condesa de Chinchón"],
    ["Las meninas", "Las hilanderas", "La Venus del espejo", "El entierro del conde de Orgaz", "El jardín de las delicias", "Guernica", "La rendición de Breda", "El caballero de la mano en el pecho", "Las tres Gracias", "Vieja friendo huevos"]],
  [2, "Arquitectos",
    ["Gaudí", "Le Corbusier", "Frank Lloyd Wright", "Zaha Hadid", "Norman Foster", "Frank Gehry", "Santiago Calatrava", "Rafael Moneo", "Mies van der Rohe", "Oscar Niemeyer", "Renzo Piano", "I. M. Pei", "Brunelleschi", "Bramante", "Walter Gropius"],
    ["Picasso", "Dalí", "Rodin", "Van Gogh", "Monet", "Andy Warhol", "Frida Kahlo", "Banksy", "Botero", "Kandinsky"]],
  [2, "Cuadros de Picasso",
    ["Guernica", "Las señoritas de Avignon", "El viejo guitarrista ciego", "La vida", "Niño con pipa", "Retrato de Gertrude Stein", "Familia de saltimbanquis", "Los tres músicos", "Mujer llorando", "El sueño", "Muchacha ante un espejo", "Dora Maar con gato", "Ciencia y caridad", "Desnudo, hojas verdes y busto", "Masacre en Corea"],
    ["La persistencia de la memoria", "El grito", "La noche estrellada", "La joven de la perla", "El beso", "El hijo del hombre", "Composición VIII", "La habitación roja", "Halcones de la noche", "Los nenúfares"]],
  [2, "Pintores del Renacimiento",
    ["Leonardo da Vinci", "Miguel Ángel", "Rafael", "Botticelli", "Tiziano", "Durero", "Masaccio", "Fra Angelico", "Piero della Francesca", "Mantegna", "Giorgione", "Giovanni Bellini", "Perugino", "Holbein", "Correggio"],
    ["Picasso", "Dalí", "Van Gogh", "Monet", "Goya", "Warhol", "Frida Kahlo", "Caravaggio", "Rembrandt", "Velázquez"]],

  // ---- Difícil ----
  [3, "Obras de Miguel Ángel",
    ["David", "La Piedad", "Bóveda de la Capilla Sixtina", "La creación de Adán", "El juicio final", "Moisés", "Cúpula de San Pedro", "Tondo Doni", "Los esclavos", "Baco", "Biblioteca Laurenciana", "Tumbas de los Médici", "Piedad Rondanini", "Plaza del Campidoglio", "Busto de Bruto"],
    ["La escuela de Atenas", "La Gioconda", "La última cena", "El nacimiento de Venus", "El rapto de Proserpina", "Éxtasis de santa Teresa", "Perseo con la cabeza de Medusa", "David de Donatello", "Las puertas del Paraíso", "Cúpula de la catedral de Florencia"]],
  [3, "Cuadros del Museo del Prado",
    ["Las meninas", "El jardín de las delicias", "El 3 de mayo", "Las hilanderas", "La maja desnuda", "El caballero de la mano en el pecho", "El descendimiento", "Las tres Gracias", "Saturno devorando a su hijo", "El cardenal", "Carlos V en Mühlberg", "La Anunciación de Fra Angelico", "El tránsito de la Virgen", "Adán y Eva de Durero", "Autorretrato de Durero"],
    ["Guernica", "La Gioconda", "La noche estrellada", "La ronda de noche", "La joven de la perla", "El nacimiento de Venus", "La persistencia de la memoria", "Los girasoles", "Impresión, sol naciente", "El entierro del conde de Orgaz"]],
  [3, "Pintores surrealistas",
    ["Dalí", "Magritte", "Max Ernst", "Miró", "Yves Tanguy", "Leonora Carrington", "Remedios Varo", "Paul Delvaux", "André Masson", "Óscar Domínguez", "Man Ray", "Dorothea Tanning", "Kay Sage", "Roberto Matta", "Wolfgang Paalen"],
    ["Monet", "Renoir", "Velázquez", "Rubens", "Vermeer", "Mondrian", "Kandinsky", "Warhol", "Pollock", "Klimt"]],
  [3, "Pintores de los Países Bajos y Flandes",
    ["Rembrandt", "Vermeer", "Rubens", "Van Dyck", "Van Eyck", "El Bosco", "Bruegel el Viejo", "Frans Hals", "Hans Memling", "Van der Weyden", "Jacob Jordaens", "Jan Steen", "Van Gogh", "Mondrian", "Escher"],
    ["Durero", "Holbein", "Cranach", "Tiziano", "Caravaggio", "Poussin", "Turner", "Constable", "Goya", "Klimt"]],
  [3, "Obras de Rodin",
    ["El pensador", "El beso", "La puerta del Infierno", "Los burgueses de Calais", "Balzac", "La edad de bronce", "San Juan Bautista predicando", "Adán", "La catedral", "Danaide", "La mano de Dios", "Monumento a Victor Hugo", "Eva", "Las tres sombras", "Fugit Amor"],
    ["David", "La Piedad", "Moisés", "El rapto de Proserpina", "Éxtasis de santa Teresa", "Perseo con la cabeza de Medusa", "Venus de Milo", "El vals", "Pájaro en el espacio", "Las tres Gracias"]],
  [3, "Partes de una catedral gótica",
    ["Arbotante", "Contrafuerte", "Rosetón", "Bóveda de crucería", "Gárgola", "Pináculo", "Vidriera", "Arco apuntado", "Nave", "Crucero", "Girola", "Ábside", "Triforio", "Claustro", "Pórtico"],
    ["Minarete", "Pagoda", "Zigurat", "Iglú", "Menhir", "Dolmen", "Tipi", "Estupa", "Mastaba", "Palafito"]],
  [3, "Cuadros de Claude Monet",
    ["Impresión, sol naciente", "Los nenúfares", "La catedral de Ruan", "El puente japonés", "Mujer con sombrilla", "La estación de Saint-Lazare", "Almiares", "El Parlamento de Londres", "Amapolas", "La urraca", "Camille con vestido verde", "Mujeres en el jardín", "Los álamos", "La calle Montorgueil"],
    ["Olympia", "El bar del Folies-Bergère", "Baile en el Moulin de la Galette", "El almuerzo de los remeros", "La clase de danza", "Los jugadores de cartas", "Tarde de domingo en la Grande Jatte", "La noche estrellada", "Los girasoles", "El ajenjo", "La montaña Sainte-Victoire"]],
  [3, "Pintores del Barroco",
    ["Caravaggio", "Rembrandt", "Rubens", "Velázquez", "Vermeer", "Zurbarán", "Murillo", "José de Ribera", "Van Dyck", "Artemisia Gentileschi", "Poussin", "Frans Hals", "Annibale Carracci", "Guido Reni", "Georges de La Tour"],
    ["Botticelli", "Leonardo da Vinci", "Rafael", "Monet", "Van Gogh", "Goya", "Picasso", "Dalí", "Giotto", "Klimt"]],
  [3, "Obras de Salvador Dalí",
    ["La persistencia de la memoria", "Cisnes que se reflejan como elefantes", "Muchacha en la ventana", "Premonición de la guerra civil", "El Cristo de san Juan de la Cruz", "La tentación de san Antonio", "Galatea de las esferas", "La Madona de Port Lligat", "Leda atómica", "El rostro de la guerra", "Los elefantes", "Corpus Hypercubus", "Sofá de los labios de Mae West", "Teléfono langosta", "El enigma sin fin"],
    ["El hijo del hombre", "Los amantes", "La traición de las imágenes", "Elefante Célebes", "Las señoritas de Avignon", "Guernica", "El carnaval de Arlequín", "Mujer y pájaro", "Composición VIII", "El grito"]],
  [3, "Esculturas famosas",
    ["El pensador", "David", "La Piedad", "Venus de Milo", "Victoria de Samotracia", "Discóbolo", "Laocoonte y sus hijos", "El rapto de Proserpina", "Éxtasis de santa Teresa", "Dama de Elche", "Moisés", "Perseo con la cabeza de Medusa", "La Sirenita de Copenhague", "Auriga de Delfos", "Los burgueses de Calais"],
    ["La Gioconda", "Las meninas", "El grito", "La noche estrellada", "Guernica", "El jardín de las delicias", "La joven de la perla", "Los girasoles", "El nacimiento de Venus", "La última cena"]],
];
