// Campo de minas · Ciencia. [difficulty, prompt, right answers, mines] (see ./index.js).
export default [
  // ---- Fácil ----
  [1, "Animales mamíferos",
    ["Perro", "Gato", "Delfín", "Ballena", "Murciélago", "Caballo", "Elefante", "León", "Vaca", "Conejo", "Ornitorrinco", "Canguro", "Oso", "Jirafa", "Foca"],
    ["Pingüino", "Tiburón", "Cocodrilo", "Águila", "Rana", "Serpiente", "Tortuga", "Pulpo", "Salmón", "Avestruz"]],
  [1, "Elementos químicos",
    ["Oxígeno", "Hidrógeno", "Carbono", "Hierro", "Oro", "Plata", "Cobre", "Helio", "Sodio", "Calcio", "Nitrógeno", "Mercurio", "Plomo", "Zinc", "Uranio"],
    ["Agua", "Acero", "Bronce", "Sal", "Petróleo", "Latón", "Plástico", "Arena", "Vidrio", "Aire"]],
  [1, "Órganos del cuerpo humano",
    ["Corazón", "Hígado", "Pulmón", "Riñón", "Cerebro", "Estómago", "Páncreas", "Bazo", "Piel", "Vejiga", "Intestino", "Ojo", "Útero", "Tiroides", "Esófago"],
    ["Branquias", "Aleta", "Antena", "Pico", "Caparazón", "Tentáculo", "Pluma", "Escama", "Cuerno", "Bolsa marsupial"]],
  [1, "Partes de una planta",
    ["Raíz", "Tallo", "Hoja", "Flor", "Fruto", "Semilla", "Pétalo", "Estambre", "Pistilo", "Sépalo", "Yema", "Corteza", "Tronco", "Rama", "Cáliz"],
    ["Pulmón", "Branquia", "Aleta", "Pluma", "Pezuña", "Antena", "Vértebra", "Hocico", "Melena", "Garra"]],
  [1, "Huesos del cuerpo humano",
    ["Fémur", "Tibia", "Peroné", "Húmero", "Cúbito", "Radio", "Clavícula", "Esternón", "Rótula", "Omóplato", "Mandíbula", "Costilla", "Vértebra", "Coxis", "Estribo"],
    ["Bíceps", "Tríceps", "Tendón", "Cartílago", "Menisco", "Glúteo", "Cuádriceps", "Aorta", "Tráquea", "Diafragma"]],
  [1, "Animales herbívoros",
    ["Vaca", "Jirafa", "Elefante", "Conejo", "Caballo", "Cebra", "Koala", "Canguro", "Rinoceronte", "Oveja", "Cabra", "Ciervo", "Camello", "Bisonte", "Manatí"],
    ["León", "Tigre", "Lobo", "Tiburón", "Águila", "Cocodrilo", "Orca", "Leopardo", "Halcón", "Hiena"]],
  [1, "Insectos",
    ["Mosca", "Mosquito", "Abeja", "Avispa", "Hormiga", "Mariposa", "Escarabajo", "Saltamontes", "Libélula", "Cucaracha", "Mariquita", "Grillo", "Polilla", "Pulga", "Termita"],
    ["Araña", "Escorpión", "Ciempiés", "Garrapata", "Cangrejo", "Caracol", "Lombriz", "Gamba", "Ácaro", "Babosa"]],
  [1, "Aves",
    ["Águila", "Gorrión", "Pingüino", "Avestruz", "Loro", "Paloma", "Búho", "Gaviota", "Flamenco", "Colibrí", "Cigüeña", "Pato", "Halcón", "Pavo real", "Kiwi"],
    ["Murciélago", "Ardilla voladora", "Pez volador", "Pterodáctilo", "Mariposa", "Libélula", "Ornitorrinco", "Abeja", "Pez loro", "Lagartija"]],
  [1, "Reptiles",
    ["Cocodrilo", "Serpiente", "Tortuga", "Lagarto", "Iguana", "Camaleón", "Caimán", "Gecko", "Dragón de Komodo", "Cobra", "Pitón", "Anaconda", "Víbora", "Lagartija", "Galápago"],
    ["Rana", "Salamandra", "Sapo", "Tritón", "Ajolote", "Anguila", "Delfín", "Musaraña", "Babosa", "Morena"]],
  [1, "Gases a temperatura ambiente",
    ["Oxígeno", "Nitrógeno", "Helio", "Hidrógeno", "Neón", "Argón", "Metano", "Propano", "Butano", "Ozono", "Cloro", "Dióxido de carbono", "Monóxido de carbono", "Xenón", "Radón"],
    ["Hierro", "Mercurio", "Agua", "Azufre", "Sal", "Carbono", "Bromo", "Cobre", "Silicio", "Oro"]],

  // ---- Media ----
  [2, "Unidades del Sistema Internacional",
    ["Metro", "Kilogramo", "Segundo", "Amperio", "Kelvin", "Mol", "Candela", "Newton", "Julio", "Vatio", "Pascal", "Voltio", "Ohmio", "Hercio", "Culombio"],
    ["Pulgada", "Milla", "Libra", "Caloría", "Caballo de vapor", "Grado Fahrenheit", "Atmósfera", "Pie", "Yarda", "Onza"]],
  [2, "Elementos que son metales",
    ["Hierro", "Cobre", "Aluminio", "Sodio", "Potasio", "Litio", "Titanio", "Wolframio", "Níquel", "Magnesio", "Cromo", "Estaño", "Platino", "Cobalto", "Zinc"],
    ["Carbono", "Azufre", "Fósforo", "Yodo", "Cloro", "Neón", "Flúor", "Oxígeno", "Selenio", "Nitrógeno"]],
  [2, "Partes de una célula",
    ["Núcleo", "Mitocondria", "Ribosoma", "Membrana", "Citoplasma", "Lisosoma", "Aparato de Golgi", "Vacuola", "Cloroplasto", "Retículo endoplasmático", "Centriolo", "Nucléolo", "Pared celular", "Citoesqueleto", "Peroxisoma"],
    ["Neurona", "Alvéolo", "Glóbulo rojo", "Plaqueta", "Nefrona", "Tendón", "Bronquio", "Folículo", "Ganglio", "Arteria"]],
  [2, "Ganadores del Premio Nobel de ciencias",
    ["Einstein", "Marie Curie", "Niels Bohr", "Max Planck", "Ramón y Cajal", "Feynman", "Fleming", "Linus Pauling", "Schrödinger", "Heisenberg", "Paul Dirac", "Enrico Fermi", "Severo Ochoa", "Peter Higgs", "James Watson"],
    ["Isaac Newton", "Galileo", "Darwin", "Nikola Tesla", "Edison", "Hawking", "Mendeléiev", "Carl Sagan", "Pasteur", "Mendel"]],
  [2, "Enfermedades causadas por virus",
    ["Gripe", "Sarampión", "Varicela", "Rabia", "Ébola", "Sida", "Hepatitis B", "Viruela", "Polio", "Paperas", "Rubeola", "Covid-19", "Dengue", "Herpes", "Fiebre amarilla"],
    ["Tuberculosis", "Cólera", "Malaria", "Tétanos", "Lepra", "Peste negra", "Sífilis", "Salmonelosis", "Difteria", "Tos ferina"]],
  [2, "Constelaciones",
    ["Orión", "Osa Mayor", "Osa Menor", "Casiopea", "Andrómeda", "Pegaso", "Escorpio", "Leo", "Tauro", "Géminis", "Cisne", "Lira", "Perseo", "Hércules", "Cruz del Sur"],
    ["Sirio", "Betelgeuse", "Vega", "Estrella Polar", "Próxima Centauri", "Vía Láctea", "Pléyades", "Cometa Halley", "Ceres", "Titán"]],
  [2, "Inventos del siglo XX",
    ["Avión", "Televisión", "Radar", "Transistor", "Láser", "Horno microondas", "Teléfono móvil", "GPS", "Nailon", "Bolígrafo", "Velcro", "Código de barras", "Satélite artificial", "Internet", "Tetrabrik"],
    ["Imprenta", "Teléfono", "Bombilla", "Máquina de vapor", "Telégrafo", "Brújula", "Fotografía", "Pararrayos", "Locomotora", "Vacuna"]],
  [2, "Lunas del sistema solar",
    ["Luna", "Fobos", "Deimos", "Ío", "Europa", "Ganímedes", "Calisto", "Titán", "Encélado", "Rea", "Tritón", "Caronte", "Miranda", "Titania", "Mimas"],
    ["Ceres", "Plutón", "Vesta", "Eris", "Sedna", "Cometa Halley", "Venus", "Sirio", "Andrómeda", "Hale-Bopp"]],
  [2, "Hormonas",
    ["Insulina", "Adrenalina", "Testosterona", "Estrógeno", "Cortisol", "Melatonina", "Tiroxina", "Oxitocina", "Progesterona", "Glucagón", "Leptina", "Prolactina", "Eritropoyetina", "Vasopresina", "Grelina"],
    ["Hemoglobina", "Colesterol", "Queratina", "Colágeno", "Pepsina", "Amilasa", "Lactosa", "Glucosa", "Bilis", "Hierro"]],
  [2, "Partes del aparato digestivo",
    ["Boca", "Esófago", "Estómago", "Duodeno", "Yeyuno", "Íleon", "Colon", "Recto", "Hígado", "Páncreas", "Vesícula biliar", "Faringe", "Ciego", "Apéndice", "Ano"],
    ["Tráquea", "Bronquios", "Alvéolos", "Riñón", "Uretra", "Vejiga", "Laringe", "Pulmón", "Diafragma", "Bazo"]],

  // ---- Difícil ----
  [3, "Elementos cuyo símbolo es una sola letra",
    ["Hidrógeno", "Boro", "Carbono", "Nitrógeno", "Oxígeno", "Flúor", "Fósforo", "Azufre", "Potasio", "Vanadio", "Itrio", "Yodo", "Wolframio", "Uranio"],
    ["Helio", "Calcio", "Sodio", "Hierro", "Cloro", "Neón", "Plata", "Oro", "Cobre", "Litio", "Magnesio"]],
  [3, "Elementos cuyo símbolo no empieza por su inicial en español",
    ["Sodio", "Potasio", "Hierro", "Plata", "Oro", "Plomo", "Estaño", "Mercurio", "Antimonio", "Azufre", "Fósforo", "Yodo"],
    ["Calcio", "Carbono", "Cobre", "Cloro", "Neón", "Litio", "Magnesio", "Helio", "Nitrógeno", "Oxígeno", "Uranio", "Zinc", "Aluminio"]],
  [3, "Unidades con nombre de un científico",
    ["Newton", "Julio", "Vatio", "Pascal", "Voltio", "Amperio", "Ohmio", "Hercio", "Kelvin", "Culombio", "Tesla", "Faradio", "Henrio", "Becquerel", "Sievert"],
    ["Metro", "Kilogramo", "Segundo", "Mol", "Candela", "Lumen", "Lux", "Litro", "Radián", "Katal"]],
  [3, "Huesos de la mano",
    ["Escafoides", "Semilunar", "Piramidal", "Pisiforme", "Trapecio", "Trapezoide", "Hueso grande", "Ganchoso", "Metacarpiano", "Falange"],
    ["Astrágalo", "Calcáneo", "Cuboides", "Cuneiforme", "Rótula", "Peroné", "Estribo", "Yunque", "Martillo", "Atlas", "Axis", "Hioides", "Sacro", "Vómer", "Etmoides"]],
  [3, "Partes del oído",
    ["Tímpano", "Martillo", "Yunque", "Estribo", "Cóclea", "Pabellón auricular", "Trompa de Eustaquio", "Conducto auditivo", "Laberinto", "Vestíbulo", "Canales semicirculares", "Ventana oval", "Órgano de Corti", "Utrículo", "Sáculo"],
    ["Retina", "Córnea", "Iris", "Cristalino", "Pupila", "Esclerótica", "Cornete", "Úvula", "Glotis", "Epiglotis"]],
  [3, "Enfermedades causadas por bacterias",
    ["Tuberculosis", "Cólera", "Tétanos", "Lepra", "Peste bubónica", "Sífilis", "Difteria", "Tos ferina", "Botulismo", "Salmonelosis", "Legionelosis", "Escarlatina", "Gonorrea", "Ántrax", "Brucelosis"],
    ["Malaria", "Gripe", "Sarampión", "Rabia", "Toxoplasmosis", "Viruela", "Polio", "Dengue", "Hepatitis A", "Pie de atleta"]],
  [3, "Partículas subatómicas",
    ["Protón", "Neutrón", "Electrón", "Quark", "Neutrino", "Muon", "Positrón", "Fotón", "Gluón", "Bosón de Higgs", "Pion", "Tau", "Bosón W", "Bosón Z", "Kaón"],
    ["Molécula", "Átomo", "Ion", "Isótopo", "Nucleótido", "Fonema", "Mitocondria", "Cromosoma", "Polímero", "Cristal"]],
  [3, "Científicos e inventores españoles",
    ["Ramón y Cajal", "Severo Ochoa", "Margarita Salas", "Isaac Peral", "Juan de la Cierva", "Torres Quevedo", "Miguel Servet", "Jorge Juan", "Andrés del Río", "Fausto Elhuyar", "Gregorio Marañón", "Francisco Mojica", "Ignacio Cirac", "Mariano Barbacid", "Arturo Duperier"],
    ["Galileo", "Fleming", "Pasteur", "Marie Curie", "Lavoisier", "Mendel", "Copérnico", "Alessandro Volta", "Linneo", "Avogadro"]],
  [3, "Marsupiales",
    ["Canguro", "Koala", "Zarigüeya", "Wombat", "Demonio de Tasmania", "Ualabí", "Petauro del azúcar", "Numbat", "Quokka", "Bandicut", "Tilacino", "Monito del monte", "Bilbi", "Cuscús"],
    ["Ornitorrinco", "Equidna", "Perezoso", "Armadillo", "Oso hormiguero", "Lémur", "Mapache", "Suricata", "Dingo", "Murciélago", "Tarsero"]],
  [3, "Ramas de la biología",
    ["Botánica", "Zoología", "Genética", "Ecología", "Microbiología", "Anatomía", "Fisiología", "Citología", "Histología", "Embriología", "Micología", "Ornitología", "Entomología", "Ictiología", "Virología"],
    ["Geología", "Sismología", "Vulcanología", "Astrología", "Numismática", "Filatelia", "Meteorología", "Mineralogía", "Cartografía", "Etimología"]],
];
