// Campo de minas · Cultura general. [difficulty, prompt, right answers, mines] (see ./index.js).
export default [
  // ---- Fácil ----
  [1, "Frutas",
    ["Manzana", "Plátano", "Naranja", "Fresa", "Uva", "Pera", "Melocotón", "Sandía", "Melón", "Piña", "Mango", "Kiwi", "Cereza", "Limón", "Papaya"],
    ["Lechuga", "Zanahoria", "Patata", "Cebolla", "Brócoli", "Espinaca", "Ajo", "Coliflor", "Apio", "Puerro"]],
  [1, "Platos típicos españoles",
    ["Paella", "Tortilla de patatas", "Gazpacho", "Cocido madrileño", "Fabada", "Pulpo a la gallega", "Salmorejo", "Croquetas", "Pisto", "Migas", "Bocadillo de calamares", "Patatas bravas", "Churros", "Crema catalana", "Pan con tomate"],
    ["Pizza", "Sushi", "Tacos", "Ramen", "Hamburguesa", "Lasaña", "Ceviche", "Musaca", "Fondue", "Gulash"]],
  [1, "Signos del zodiaco",
    ["Aries", "Tauro", "Géminis", "Cáncer", "Leo", "Virgo", "Libra", "Escorpio", "Sagitario", "Capricornio", "Acuario", "Piscis"],
    ["Dragón", "Tigre", "Serpiente", "Mono", "Gallo", "Rata", "Ofiuco", "Orión", "Pegaso", "Casiopea", "Andrómeda", "Osa Mayor", "Fénix"]],
  [1, "Idiomas que existen",
    ["Español", "Inglés", "Francés", "Alemán", "Italiano", "Portugués", "Chino mandarín", "Japonés", "Árabe", "Ruso", "Hindi", "Catalán", "Euskera", "Gallego", "Suajili"],
    ["Brasileño", "Austríaco", "Argentino", "Suizo", "Belga", "Estadounidense", "Canadiense", "Australiano", "Colombiano", "Chileno"]],
  [1, "Animales que viven en el mar",
    ["Tiburón", "Delfín", "Ballena", "Pulpo", "Medusa", "Estrella de mar", "Calamar", "Orca", "Caballito de mar", "Pez espada", "Atún", "Mantarraya", "Erizo de mar", "Sepia", "Coral"],
    ["Camello", "Jirafa", "Elefante", "Canguro", "León", "Cebra", "Koala", "Hipopótamo", "Tigre", "Oso panda"]],
  [1, "Fiestas y tradiciones de España",
    ["San Fermín", "Las Fallas", "La Tomatina", "Semana Santa", "Feria de Abril", "Carnaval de Cádiz", "Moros y Cristianos", "Noche de San Juan", "Cabalgata de Reyes", "Romería del Rocío", "Hogueras de Alicante", "Sant Jordi", "Carnaval de Tenerife", "Batalla del Vino de Haro", "Castellers"],
    ["Oktoberfest", "Acción de Gracias", "Día de Muertos", "Año Nuevo chino", "Holi", "Carnaval de Río", "Diwali", "Hanami", "Inti Raymi", "Songkran"]],
  [1, "Cosas que hay en una cocina",
    ["Nevera", "Horno", "Microondas", "Sartén", "Cazo", "Olla", "Tostadora", "Batidora", "Fregadero", "Cuchillo", "Tabla de cortar", "Lavavajillas", "Extractor", "Cafetera", "Rallador"],
    ["Ducha", "Bañera", "Inodoro", "Bidé", "Cama", "Almohada", "Armario ropero", "Mesita de noche", "Escritorio", "Perchero"]],
  [1, "Monedas que se usan hoy",
    ["Euro", "Dólar", "Libra esterlina", "Yen", "Yuan", "Rublo", "Peso", "Rupia", "Franco suizo", "Real brasileño", "Corona sueca", "Won", "Lira turca", "Zloty", "Dírham"],
    ["Peseta", "Marco alemán", "Franco francés", "Lira italiana", "Dracma", "Escudo portugués", "Florín neerlandés", "Ecu", "Doblón", "Maravedí"]],
  [1, "Herramientas",
    ["Martillo", "Destornillador", "Alicates", "Llave inglesa", "Sierra", "Taladro", "Serrucho", "Lima", "Cincel", "Nivel", "Cinta métrica", "Tenazas", "Pala", "Rastrillo", "Hacha"],
    ["Tenedor", "Cuchara", "Plato", "Vaso", "Taza", "Servilleta", "Mantel", "Jarra", "Bol", "Tetera"]],
  [1, "Juegos de mesa",
    ["Ajedrez", "Parchís", "Monopoly", "Trivial", "Scrabble", "Damas", "Oca", "Cluedo", "Risk", "Catan", "Pictionary", "Dominó", "Backgammon", "Jenga", "Dixit"],
    ["Fútbol", "Tenis", "Escondite", "Rayuela", "Pilla pilla", "Comba", "Fortnite", "Tetris", "Minecraft", "Pac-Man"]],

  // ---- Media ----
  [2, "Dioses egipcios",
    ["Ra", "Osiris", "Isis", "Horus", "Anubis", "Set", "Thot", "Ptah", "Hathor", "Bastet", "Sobek", "Amón", "Maat", "Atón", "Neftis"],
    ["Zeus", "Odín", "Júpiter", "Thor", "Apolo", "Quetzalcóatl", "Vishnu", "Marduk", "Inti", "Hades"]],
  [2, "Criaturas mitológicas",
    ["Minotauro", "Medusa", "Pegaso", "Centauro", "Quimera", "Hidra", "Fénix", "Cíclope", "Grifo", "Esfinge", "Sirena", "Cerbero", "Kraken", "Unicornio", "Basilisco"],
    ["Ornitorrinco", "Ajolote", "Okapi", "Narval", "Dodo", "Mamut", "Calamar gigante", "Pangolín", "Tapir", "Quetzal"]],
  [2, "Religiones",
    ["Cristianismo", "Islam", "Judaísmo", "Budismo", "Hinduismo", "Sijismo", "Taoísmo", "Sintoísmo", "Jainismo", "Zoroastrismo", "Bahaísmo", "Candomblé", "Vudú", "Rastafarismo", "Santería"],
    ["Estoicismo", "Existencialismo", "Marxismo", "Nihilismo", "Positivismo", "Empirismo", "Racionalismo", "Utilitarismo", "Epicureísmo", "Cinismo"]],
  [2, "Cosas de la cultura japonesa",
    ["Sushi", "Kimono", "Samurái", "Origami", "Haiku", "Manga", "Anime", "Karaoke", "Sake", "Geisha", "Ikebana", "Bonsái", "Sumo", "Ninja", "Katana"],
    ["Tango", "Flamenco", "Taco", "Kilt", "Matrioska", "Sirtaki", "Haggis", "Capoeira", "Didgeridoo", "Yoga"]],
  [2, "Quesos",
    ["Manchego", "Roquefort", "Brie", "Camembert", "Parmesano", "Mozzarella", "Gouda", "Emmental", "Cabrales", "Idiazábal", "Gorgonzola", "Cheddar", "Feta", "Torta del Casar", "Mahón"],
    ["Jamón ibérico", "Chorizo", "Fuet", "Sobrasada", "Lomo embuchado", "Salami", "Mortadela", "Prosciutto", "Morcilla", "Cecina"]],
  [2, "Cócteles",
    ["Mojito", "Margarita", "Piña colada", "Daiquiri", "Cosmopolitan", "Bloody Mary", "Caipiriña", "Dry Martini", "Negroni", "Pisco sour", "Manhattan", "Tequila Sunrise", "Mai Tai", "Old Fashioned", "Cuba libre"],
    ["Rioja", "Cava", "Champán", "Oporto", "Jerez", "Sidra", "Kombucha", "Horchata", "Kéfir", "Mate"]],
  [2, "Bailes",
    ["Salsa", "Tango", "Flamenco", "Vals", "Bachata", "Merengue", "Chachachá", "Rumba", "Samba", "Ballet", "Breakdance", "Sevillanas", "Jota", "Claqué", "Foxtrot"],
    ["Sudoku", "Origami", "Haiku", "Esgrima", "Judo", "Kárate", "Yoga", "Pilates", "Crossfit", "Ikebana"]],
  [2, "Personajes de la Biblia",
    ["Moisés", "Abraham", "Noé", "David", "Goliat", "Salomón", "Sansón", "Dalila", "Adán", "Eva", "Caín", "Abel", "Jonás", "Judas", "Pedro"],
    ["Hércules", "Ulises", "Aquiles", "Perseo", "Gilgamesh", "Rómulo", "Teseo", "Edipo", "Jasón", "Orfeo"]],
  [2, "Palabras que vienen del árabe",
    ["Almohada", "Aceite", "Azúcar", "Ojalá", "Alcalde", "Aldea", "Algodón", "Arroz", "Azulejo", "Albañil", "Alfombra", "Ajedrez", "Naranja", "Zanahoria", "Jarra"],
    ["Chocolate", "Tomate", "Patata", "Hamaca", "Canoa", "Huracán", "Fútbol", "Sándwich", "Champú", "Kiosco"]],
  [2, "Juegos de cartas",
    ["Mus", "Tute", "Brisca", "Chinchón", "Póker", "Solitario", "Blackjack", "Uno", "Escoba", "Bridge", "Canasta", "Cinquillo", "Siete y medio", "Burro", "Rummy"],
    ["Parchís", "Oca", "Ajedrez", "Damas", "Dominó", "Monopoly", "Trivial", "Scrabble", "Backgammon", "Bingo"]],

  // ---- Difícil ----
  [3, "Inventos españoles",
    ["Fregona", "Chupa Chups", "Autogiro", "Talgo", "El Ajedrecista", "Telekino", "Laringoscopio", "Escafandra estratonáutica", "Submarino de Peral"],
    ["Bolígrafo", "Teléfono", "Bombilla", "Televisión", "Radio", "Internet", "Imprenta", "Penicilina", "Avión", "Dinamita", "Velcro", "Post-it", "Cremallera", "Telescopio", "Fotografía", "Automóvil"]],
  [3, "Fobias",
    ["Aracnofobia", "Claustrofobia", "Agorafobia", "Acrofobia", "Hidrofobia", "Xenofobia", "Nictofobia", "Glosofobia", "Hematofobia", "Aerofobia", "Cinofobia", "Ofidiofobia", "Tripofobia", "Coulrofobia", "Fotofobia"],
    ["Bibliofilia", "Cleptomanía", "Megalomanía", "Piromanía", "Hipocondría", "Insomnio", "Narcolepsia", "Dislexia", "Sinestesia", "Anorexia"]],
  [3, "Palabras que vienen del náhuatl",
    ["Chocolate", "Tomate", "Aguacate", "Chicle", "Cacahuete", "Chile", "Coyote", "Tiza", "Cacao", "Hule", "Petaca", "Mapache", "Ocelote", "Achiote", "Guajolote"],
    ["Patata", "Hamaca", "Canoa", "Huracán", "Cóndor", "Llama", "Puma", "Alpaca", "Caníbal", "Barbacoa"]],
  [3, "Filósofos de la antigua Grecia",
    ["Sócrates", "Platón", "Aristóteles", "Tales de Mileto", "Pitágoras", "Heráclito", "Parménides", "Demócrito", "Epicuro", "Zenón", "Diógenes", "Anaximandro", "Empédocles", "Protágoras", "Anaxágoras"],
    ["Séneca", "Cicerón", "Lucrecio", "Descartes", "Kant", "Nietzsche", "Confucio", "Spinoza", "Hegel", "Maquiavelo"]],
  [3, "Denominaciones de origen de vino españolas",
    ["Rioja", "Ribera del Duero", "Priorat", "Rías Baixas", "Jerez", "Rueda", "Toro", "Penedès", "Somontano", "Bierzo", "Getariako Txakolina", "Jumilla", "Valdepeñas", "La Mancha", "Cava"],
    ["Burdeos", "Champagne", "Borgoña", "Chianti", "Oporto", "Douro", "Mosela", "Napa Valley", "Mendoza", "Tokaji"]],
  [3, "Instrumentos de navegación",
    ["Brújula", "Astrolabio", "Sextante", "Octante", "Cuadrante", "Ballestilla", "Cronómetro marino", "Corredera", "Sonda", "Radar", "GPS", "Sonar", "Carta náutica", "Girocompás", "Loran"],
    ["Estetoscopio", "Sismógrafo", "Microscopio", "Metrónomo", "Telar", "Ábaco", "Pantógrafo", "Oftalmoscopio", "Esfigmomanómetro", "Fonendoscopio"]],
  [3, "Órdenes religiosas católicas",
    ["Franciscanos", "Dominicos", "Jesuitas", "Benedictinos", "Cartujos", "Carmelitas", "Agustinos", "Cistercienses", "Trapenses", "Clarisas", "Salesianos", "Escolapios", "Mercedarios", "Jerónimos", "Templarios"],
    ["Masones", "Rosacruces", "Illuminati", "Cátaros", "Hugonotes", "Anabaptistas", "Mormones", "Cuáqueros", "Amish", "Testigos de Jehová"]],
  [3, "Palabras que vienen del inglés",
    ["Fútbol", "Líder", "Mitin", "Túnel", "Club", "Bistec", "Cóctel", "Esnob", "Yate", "Récord", "Suéter", "Váter", "Sándwich", "Estrés", "Dólar"],
    ["Ojalá", "Almohada", "Chocolate", "Tomate", "Hamaca", "Kiosco", "Garaje", "Balcón", "Piano", "Bricolaje"]],
  [3, "Signos de puntuación",
    ["Punto", "Coma", "Punto y coma", "Dos puntos", "Paréntesis", "Corchetes", "Raya", "Comillas", "Signo de interrogación", "Signo de exclamación", "Puntos suspensivos"],
    ["Arroba", "Almohadilla", "Ampersand", "Porcentaje", "Símbolo del dólar", "Signo más", "Signo igual", "Símbolo de grado", "Símbolo del euro", "Copyright", "Signo menos", "Signo de multiplicar", "Raíz cuadrada", "Infinito"]],
  [3, "Patrimonio de la Humanidad en España",
    ["Alhambra", "Mezquita de Córdoba", "Catedral de Burgos", "Acueducto de Segovia", "El Escorial", "Park Güell", "Cuevas de Altamira", "Toledo", "Salamanca", "Palmeral de Elche", "Torre de Hércules", "Camino de Santiago", "Parque Nacional del Teide", "Doñana", "Ibiza"],
    ["Guggenheim Bilbao", "Puerta del Sol", "Torres Kio", "Ciudad de las Artes y las Ciencias", "Plaza de España de Sevilla", "Santiago Bernabéu", "Gran Vía", "Benidorm", "Puerto Banús", "Palacio Real de Madrid"]],
];
