// Campo de minas · Deportes. [difficulty, prompt, right answers, mines] (see ./index.js).
// Records that can still change (titles, medals) only use players and teams whose answer can't change any more.
export default [
  // ---- Fácil ----
  [1, "Deportes de los Juegos Olímpicos de verano",
    ["Atletismo", "Natación", "Gimnasia", "Fútbol", "Baloncesto", "Tenis", "Ciclismo", "Boxeo", "Judo", "Esgrima", "Remo", "Vela", "Tiro con arco", "Voleibol", "Balonmano"],
    ["Ajedrez", "Pádel", "Dardos", "Billar", "Petanca", "Bolos", "Fórmula 1", "Sumo", "Motociclismo", "Rally"]],
  [1, "Futbolistas",
    ["Messi", "Cristiano Ronaldo", "Pelé", "Maradona", "Zidane", "Iniesta", "Xavi", "Ronaldinho", "Neymar", "Mbappé", "Haaland", "Lewandowski", "Modric", "Casillas", "Sergio Ramos"],
    ["Michael Jordan", "Rafa Nadal", "Usain Bolt", "Fernando Alonso", "Tiger Woods", "LeBron James", "Pau Gasol", "Roger Federer", "Marc Márquez", "Simone Biles"]],
  [1, "Equipos de fútbol españoles",
    ["Real Madrid", "Barcelona", "Atlético de Madrid", "Sevilla", "Valencia", "Athletic Club", "Real Sociedad", "Betis", "Villarreal", "Celta", "Osasuna", "Getafe", "Espanyol", "Deportivo", "Rayo Vallecano"],
    ["Juventus", "Bayern de Múnich", "Manchester United", "Liverpool", "PSG", "Boca Juniors", "Benfica", "Ajax", "Milan", "Chelsea"]],
  [1, "Tenistas",
    ["Rafa Nadal", "Roger Federer", "Novak Djokovic", "Carlos Alcaraz", "Serena Williams", "Venus Williams", "Andy Murray", "Pete Sampras", "Andre Agassi", "Steffi Graf", "Arantxa Sánchez Vicario", "Conchita Martínez", "Jannik Sinner", "Garbiñe Muguruza", "Maria Sharapova"],
    ["Lionel Messi", "Michael Phelps", "Tiger Woods", "Pau Gasol", "Fernando Alonso", "Usain Bolt", "Kobe Bryant", "Valentino Rossi", "Mike Tyson", "Cristiano Ronaldo"]],
  [1, "Deportes que se juegan con balón o pelota",
    ["Fútbol", "Baloncesto", "Tenis", "Voleibol", "Balonmano", "Rugby", "Golf", "Béisbol", "Waterpolo", "Pádel", "Squash", "Pelota vasca", "Ping-pong", "Críquet", "Fútbol americano"],
    ["Natación", "Atletismo", "Ciclismo", "Boxeo", "Judo", "Esgrima", "Esquí", "Remo", "Hockey sobre hielo", "Bádminton"]],
  [1, "Pilotos de Fórmula 1",
    ["Fernando Alonso", "Lewis Hamilton", "Michael Schumacher", "Ayrton Senna", "Max Verstappen", "Sebastian Vettel", "Carlos Sainz", "Charles Leclerc", "Kimi Räikkönen", "Niki Lauda", "Alain Prost", "Lando Norris", "Nico Rosberg", "Checo Pérez", "Mika Häkkinen"],
    ["Marc Márquez", "Valentino Rossi", "Jorge Lorenzo", "Dani Pedrosa", "Sébastien Loeb", "Nani Roma", "Ángel Nieto", "Miguel Induráin", "Tadej Pogačar", "Mick Doohan"]],
  [1, "Deportes de invierno",
    ["Esquí alpino", "Snowboard", "Patinaje sobre hielo", "Hockey sobre hielo", "Curling", "Bobsleigh", "Luge", "Biatlón", "Salto de esquí", "Skeleton", "Esquí de fondo", "Patinaje artístico", "Combinada nórdica", "Esquí acrobático", "Patinaje de velocidad"],
    ["Surf", "Windsurf", "Waterpolo", "Remo", "Vela", "Natación", "Piragüismo", "Vóley playa", "Triatlón", "Golf"]],
  [1, "Jugadores de baloncesto",
    ["Michael Jordan", "LeBron James", "Kobe Bryant", "Pau Gasol", "Marc Gasol", "Magic Johnson", "Larry Bird", "Stephen Curry", "Shaquille O'Neal", "Kareem Abdul-Jabbar", "Dirk Nowitzki", "Luka Dončić", "Ricky Rubio", "Juan Carlos Navarro", "Tim Duncan"],
    ["Lionel Messi", "Rafa Nadal", "Usain Bolt", "Tiger Woods", "Fernando Alonso", "Cristiano Ronaldo", "Michael Phelps", "Mike Tyson", "Roger Federer", "Diego Maradona"]],
  [1, "Cosas de un partido de fútbol",
    ["Balón", "Portería", "Red", "Banderín de córner", "Silbato", "Tarjeta roja", "Tarjeta amarilla", "Espinilleras", "Botas de tacos", "Guantes de portero", "Brazalete de capitán", "Banquillo", "VAR", "Línea de fondo", "Círculo central"],
    ["Raqueta", "Canasta", "Palo de golf", "Bate", "Tablero", "Disco de hockey", "Volante de bádminton", "Taco de billar", "Sillín", "Esquís"]],
  [1, "Ciclistas",
    ["Miguel Induráin", "Eddy Merckx", "Lance Armstrong", "Alberto Contador", "Pedro Delgado", "Tadej Pogačar", "Jonas Vingegaard", "Chris Froome", "Bernard Hinault", "Federico Bahamontes", "Alejandro Valverde", "Óscar Freire", "Marco Pantani", "Fausto Coppi", "Peter Sagan"],
    ["Usain Bolt", "Michael Phelps", "Rafa Nadal", "Fernando Alonso", "Valentino Rossi", "Pau Gasol", "Fermín Cacho", "Mo Farah", "Carolina Marín", "David Ferrer"]],

  // ---- Media ----
  [2, "Selecciones campeonas del Mundial de fútbol",
    ["Brasil", "Alemania", "Italia", "Argentina", "Francia", "Uruguay", "Inglaterra", "España"],
    ["Países Bajos", "Portugal", "Croacia", "México", "Bélgica", "Suecia", "Hungría", "Colombia", "Chile", "Estados Unidos", "Japón", "Corea del Sur", "Marruecos", "Turquía", "Polonia", "Dinamarca", "Suiza"]],
  [2, "Equipos de la NBA",
    ["Lakers", "Celtics", "Bulls", "Warriors", "Heat", "Knicks", "Spurs", "Nets", "Mavericks", "Rockets", "Suns", "Bucks", "Nuggets", "Clippers", "Thunder"],
    ["Yankees", "Dodgers", "Patriots", "Cowboys", "Red Sox", "Packers", "Steelers", "Cubs", "Rangers", "Maple Leafs"]],
  [2, "Ganadores del Balón de Oro",
    ["Messi", "Cristiano Ronaldo", "Modric", "Benzema", "Zidane", "Ronaldinho", "Kaká", "Rodri", "Luís Figo", "Rivaldo", "Ronaldo Nazário", "Michael Owen", "Nedvěd", "Shevchenko", "Cannavaro"],
    ["Xavi", "Iniesta", "Raúl", "Casillas", "Maldini", "Thierry Henry", "Totti", "Buffon", "Ibrahimović", "Pirlo"]],
  [2, "Ganadores del Tour de Francia",
    ["Miguel Induráin", "Eddy Merckx", "Bernard Hinault", "Jacques Anquetil", "Alberto Contador", "Pedro Delgado", "Federico Bahamontes", "Carlos Sastre", "Óscar Pereiro", "Tadej Pogačar", "Jonas Vingegaard", "Chris Froome", "Greg LeMond", "Marco Pantani", "Egan Bernal"],
    ["Alejandro Valverde", "Joaquim Rodríguez", "Peter Sagan", "Mark Cavendish", "Raymond Poulidor", "Óscar Freire", "Joseba Beloki", "Erik Zabel", "Mario Cipollini", "Abraham Olano"]],
  [2, "Estadios de fútbol",
    ["Santiago Bernabéu", "Camp Nou", "Metropolitano", "Wembley", "Old Trafford", "Anfield", "San Siro", "Maracaná", "La Bombonera", "Allianz Arena", "Signal Iduna Park", "Mestalla", "San Mamés", "Parque de los Príncipes", "Estadio Azteca"],
    ["Madison Square Garden", "Wimbledon", "Roland Garros", "Le Mans", "Monza", "Montmeló", "Augusta National", "Palau Sant Jordi", "Silverstone", "Fenway Park"]],
  [2, "Pruebas de atletismo",
    ["100 metros", "Maratón", "Salto de altura", "Salto de longitud", "Salto con pértiga", "Triple salto", "Lanzamiento de peso", "Lanzamiento de disco", "Lanzamiento de jabalina", "Lanzamiento de martillo", "Decatlón", "Heptatlón", "110 metros vallas", "3000 metros obstáculos", "Marcha"],
    ["Mariposa", "Braza", "Espalda", "Crol", "Barra fija", "Caballo con arcos", "Florete", "Sable", "Contrarreloj", "Keirin"]],
  [2, "Términos del tenis",
    ["Ace", "Saque", "Volea", "Revés", "Derecha", "Dejada", "Globo", "Smash", "Set", "Tie-break", "Break", "Doble falta", "Passing shot", "Juego en blanco", "Bola de partido"],
    ["Penalti", "Córner", "Fuera de juego", "Triple", "Mate", "Home run", "Touchdown", "Birdie", "Jaque mate", "Hat-trick"]],
  [2, "Medallistas olímpicos españoles",
    ["Mireia Belmonte", "Carolina Marín", "Rafa Nadal", "Saúl Craviotto", "David Cal", "Fermín Cacho", "Pau Gasol", "Marcus Cooper", "Ona Carbonell", "Gemma Mengual", "Lydia Valentín", "Ruth Beitia", "Joel González", "Arantxa Sánchez Vicario", "Theresa Zabell"],
    ["Fernando Alonso", "Marc Márquez", "Pedro Delgado", "Seve Ballesteros", "Jorge Martín", "Garbiñe Muguruza", "Carlos Sainz", "Alberto Contador", "Dani Pedrosa", "Jon Rahm"]],
  [2, "Aparatos y modalidades de gimnasia",
    ["Suelo", "Barra fija", "Paralelas", "Anillas", "Caballo con arcos", "Salto de potro", "Barra de equilibrio", "Asimétricas", "Trampolín", "Cuerda", "Aro", "Pelota", "Mazas", "Cinta", "Gimnasia acrobática"],
    ["Florete", "Sable", "Espada", "Pértiga", "Jabalina", "Martillo", "Kayak", "Keirin", "Doma clásica", "Contrarreloj"]],
  [2, "Pilotos de motociclismo",
    ["Valentino Rossi", "Marc Márquez", "Jorge Lorenzo", "Dani Pedrosa", "Ángel Nieto", "Casey Stoner", "Mick Doohan", "Kenny Roberts", "Wayne Rainey", "Àlex Crivillé", "Pecco Bagnaia", "Jorge Martín", "Fabio Quartararo", "Joan Mir", "Giacomo Agostini"],
    ["Fernando Alonso", "Lewis Hamilton", "Carlos Sainz", "Sébastien Loeb", "Ayrton Senna", "Michael Schumacher", "Max Verstappen", "Kimi Räikkönen", "Niki Lauda", "Alain Prost"]],

  // ---- Difícil ----
  [3, "Campeones del mundo de Fórmula 1",
    ["Fangio", "Ayrton Senna", "Alain Prost", "Niki Lauda", "Michael Schumacher", "Fernando Alonso", "Lewis Hamilton", "Sebastian Vettel", "Max Verstappen", "Kimi Räikkönen", "Mika Häkkinen", "Jim Clark", "Jackie Stewart", "Nelson Piquet", "Nico Rosberg"],
    ["Stirling Moss", "Jarno Trulli", "Rubens Barrichello", "David Coulthard", "Gilles Villeneuve", "Mark Webber", "Felipe Massa", "Ralf Schumacher", "Pedro de la Rosa", "Juan Pablo Montoya"]],
  [3, "Ganadores de Roland Garros",
    ["Rafa Nadal", "Novak Djokovic", "Roger Federer", "Carlos Alcaraz", "Sergi Bruguera", "Carlos Moyá", "Albert Costa", "Juan Carlos Ferrero", "Arantxa Sánchez Vicario", "Gustavo Kuerten", "Björn Borg", "Iga Świątek", "Steffi Graf", "Manolo Santana", "Andrés Gimeno"],
    ["Conchita Martínez", "Pete Sampras", "Boris Becker", "Stefan Edberg", "John McEnroe", "Jimmy Connors", "Andy Murray", "David Ferrer", "Àlex Corretja", "Lleyton Hewitt"]],
  [3, "Campeones de la Copa de Europa o Champions",
    ["Real Madrid", "Barcelona", "Milan", "Bayern de Múnich", "Liverpool", "Ajax", "Inter", "Manchester United", "Juventus", "Benfica", "Chelsea", "Oporto", "Nottingham Forest", "Steaua de Bucarest", "PSG"],
    ["Valencia", "Stade de Reims", "Fiorentina", "Leeds United", "Malmö", "Saint-Étienne", "Sampdoria", "Boca Juniors", "River Plate", "Flamengo"]],
  [3, "Jugadores de España en el Mundial 2010",
    ["Casillas", "Puyol", "Piqué", "Sergio Ramos", "Capdevila", "Busquets", "Xabi Alonso", "Xavi", "Iniesta", "David Villa", "Fernando Torres", "Cesc Fàbregas", "Pedro", "Jesús Navas", "Víctor Valdés"],
    ["Raúl", "Guti", "Marcos Senna", "Santi Cazorla", "Joaquín", "Morientes", "Fernando Hierro", "Luis Enrique", "Rodri", "Lamine Yamal"]],
  [3, "Porteros de fútbol",
    ["Casillas", "Buffon", "Neuer", "Courtois", "Oblak", "Zubizarreta", "Lev Yashin", "Peter Schmeichel", "Oliver Kahn", "Dida", "Víctor Valdés", "Petr Čech", "Van der Sar", "David de Gea", "Donnarumma"],
    ["Puyol", "Maldini", "Beckenbauer", "Franco Baresi", "Sergio Ramos", "Piqué", "Cafú", "Roberto Carlos", "Cannavaro", "Fernando Hierro"]],
  [3, "Ganadores de la Vuelta a España",
    ["Alberto Contador", "Pedro Delgado", "Abraham Olano", "Roberto Heras", "Alejandro Valverde", "Chris Froome", "Primož Roglič", "Bernard Hinault", "Jacques Anquetil", "Eddy Merckx", "Tony Rominger", "Laurent Jalabert", "Vincenzo Nibali", "Sepp Kuss", "Álvaro Pino"],
    ["Miguel Induráin", "Federico Bahamontes", "Joaquim Rodríguez", "Óscar Freire", "Carlos Sastre", "Joseba Beloki", "Peter Sagan", "Mark Cavendish", "Marco Pantani", "Greg LeMond"]],
  [3, "Selecciones campeonas de la Eurocopa",
    ["Alemania", "España", "Francia", "Italia", "Unión Soviética", "Checoslovaquia", "Países Bajos", "Dinamarca", "Grecia", "Portugal"],
    ["Yugoslavia", "Alemania Oriental", "Irlanda del Norte", "Gales", "Escocia", "Islandia", "Noruega", "Finlandia", "Bulgaria", "Rumanía", "Hungría", "Austria", "Eslovenia", "Albania", "Brasil"]],
  [3, "Términos del golf",
    ["Birdie", "Eagle", "Bogey", "Par", "Albatros", "Hoyo en uno", "Green", "Bunker", "Fairway", "Caddie", "Drive", "Putt", "Hándicap", "Tee", "Hierro"],
    ["Smash", "Volea", "Touchdown", "Home run", "Spare", "Penalti", "Córner", "Mate", "Hat-trick", "Knockout"]],
  [3, "Ciudades que organizaron unos Juegos Olímpicos de verano",
    ["Atenas", "París", "San Luis", "Londres", "Estocolmo", "Amberes", "Ámsterdam", "Los Ángeles", "Berlín", "Helsinki", "Melbourne", "Múnich", "Montreal", "Seúl", "Atlanta"],
    ["Chamonix", "Sochi", "Turín", "Sarajevo", "Lake Placid", "Calgary", "Vancouver", "Albertville", "Lillehammer", "Nagano"]],
  [3, "Deportistas con más de 10 medallas olímpicas",
    ["Michael Phelps", "Larisa Latynina", "Nikolai Andrianov", "Paavo Nurmi", "Birgit Fischer", "Ryan Lochte", "Jenny Thompson", "Katie Ledecky", "Marit Bjørgen", "Ole Einar Bjørndalen", "Simone Biles", "Ireen Wüst", "Dara Torres", "Natalie Coughlin", "Sawao Kato"],
    ["Usain Bolt", "Carl Lewis", "Nadia Comăneci", "Mireia Belmonte", "Rafa Nadal", "Haile Gebrselassie", "Jesse Owens", "Ian Thorpe", "Sebastian Coe", "Mo Farah"]],
];
