// Campo de minas · Geografía. [difficulty, prompt, right answers, mines] (see ./index.js).
// Countries split between continents (Turquía, Rusia, Egipto...) and disputed capitals are left out on purpose.
export default [
  // ---- Fácil ----
  [1, "Países de Europa",
    ["España", "Francia", "Italia", "Alemania", "Portugal", "Reino Unido", "Irlanda", "Países Bajos", "Bélgica", "Suiza", "Austria", "Polonia", "Grecia", "Suecia", "Noruega"],
    ["Marruecos", "Egipto", "Brasil", "Canadá", "Japón", "Australia", "México", "Argentina", "India", "Sudáfrica"]],
  [1, "Capitales europeas",
    ["Madrid", "París", "Roma", "Berlín", "Lisboa", "Londres", "Dublín", "Ámsterdam", "Bruselas", "Viena", "Varsovia", "Atenas", "Estocolmo", "Oslo", "Praga"],
    ["Barcelona", "Milán", "Múnich", "Oporto", "Mánchester", "Zúrich", "Estambul", "Ginebra", "Róterdam", "Cracovia"]],
  [1, "Países de América",
    ["México", "Brasil", "Argentina", "Chile", "Perú", "Colombia", "Venezuela", "Cuba", "Canadá", "Estados Unidos", "Uruguay", "Bolivia", "Ecuador", "Paraguay", "Panamá"],
    ["España", "Portugal", "Filipinas", "Guinea Ecuatorial", "Marruecos", "Italia", "Angola", "Mozambique", "Australia", "Nueva Zelanda"]],
  [1, "Ríos",
    ["Amazonas", "Nilo", "Misisipi", "Danubio", "Ebro", "Tajo", "Guadalquivir", "Sena", "Rin", "Támesis", "Volga", "Yangtsé", "Ganges", "Duero", "Miño"],
    ["Titicaca", "Mediterráneo", "Caspio", "Everest", "Sahara", "Gobi", "Kilimanjaro", "Aconcagua", "Báltico", "Ladoga"]],
  [1, "Comunidades autónomas de España",
    ["Andalucía", "Cataluña", "Galicia", "Aragón", "Castilla y León", "Castilla-La Mancha", "Extremadura", "Comunidad de Madrid", "Comunidad Valenciana", "Región de Murcia", "Asturias", "Cantabria", "País Vasco", "Navarra", "La Rioja"],
    ["Algarve", "Bretaña", "Toscana", "Baviera", "Provenza", "Normandía", "Gales", "Escocia", "Flandes", "Lombardía"]],
  [1, "Océanos y mares",
    ["Atlántico", "Pacífico", "Índico", "Ártico", "Antártico", "Mediterráneo", "Caribe", "Báltico", "Mar del Norte", "Mar Negro", "Mar Rojo", "Cantábrico", "Mar de Japón", "Mar Arábigo", "Mar Egeo"],
    ["Amazonas", "Nilo", "Titicaca", "Tanganica", "Baikal", "Everest", "Sahara", "Danubio", "Misisipi", "Ontario"]],
  [1, "Países de África",
    ["Marruecos", "Egipto", "Nigeria", "Kenia", "Sudáfrica", "Etiopía", "Argelia", "Túnez", "Senegal", "Ghana", "Camerún", "Angola", "Mozambique", "Madagascar", "Tanzania"],
    ["Jamaica", "Haití", "Brasil", "India", "Arabia Saudí", "Irán", "Pakistán", "Cuba", "Indonesia", "Yemen"]],
  [1, "Grandes ciudades de Estados Unidos",
    ["Nueva York", "Los Ángeles", "Chicago", "Miami", "Houston", "San Francisco", "Las Vegas", "Boston", "Seattle", "Washington", "Filadelfia", "Dallas", "Nueva Orleans", "Atlanta", "Detroit"],
    ["Toronto", "Montreal", "Ciudad de México", "Guadalajara", "La Habana", "Sídney", "Ottawa", "Tijuana", "Monterrey", "Calgary"]],
  [1, "Montañas y cordilleras",
    ["Everest", "K2", "Aconcagua", "Kilimanjaro", "Mont Blanc", "Teide", "Mulhacén", "Aneto", "Himalaya", "Andes", "Alpes", "Pirineos", "Montañas Rocosas", "Urales", "Atlas"],
    ["Sahara", "Amazonas", "Nilo", "Gobi", "Kalahari", "Titicaca", "Mediterráneo", "Danubio", "Atacama", "Patagonia"]],
  [1, "Islas",
    ["Mallorca", "Tenerife", "Sicilia", "Cerdeña", "Córcega", "Creta", "Islandia", "Groenlandia", "Madagascar", "Cuba", "Jamaica", "Bali", "Ibiza", "Gran Canaria", "Irlanda"],
    ["Gibraltar", "Crimea", "Jutlandia", "Escandinavia", "Alaska", "Yucatán", "Florida", "Baja California", "Cornualles", "Bretaña"]],

  // ---- Media ----
  [2, "Capitales de América",
    ["Buenos Aires", "Santiago", "Lima", "Bogotá", "Caracas", "Quito", "Montevideo", "Asunción", "Brasilia", "Ottawa", "Washington D. C.", "Ciudad de México", "La Habana", "San José", "Managua"],
    ["Río de Janeiro", "São Paulo", "Nueva York", "Toronto", "Guadalajara", "Medellín", "Guayaquil", "Cartagena", "Rosario", "Montreal"]],
  [2, "Países que limitan con Alemania",
    ["Dinamarca", "Polonia", "República Checa", "Austria", "Suiza", "Francia", "Luxemburgo", "Bélgica", "Países Bajos"],
    ["España", "Italia", "Hungría", "Eslovaquia", "Suecia", "Noruega", "Liechtenstein", "Eslovenia", "Reino Unido", "Lituania", "Croacia", "Portugal", "Bielorrusia", "Ucrania", "Rumanía", "Mónaco"]],
  [2, "Capitales de Asia",
    ["Tokio", "Pekín", "Seúl", "Nueva Delhi", "Bangkok", "Hanói", "Manila", "Kabul", "Teherán", "Bagdad", "Riad", "Katmandú", "Islamabad", "Ulán Bator", "Taskent"],
    ["Shanghái", "Bombay", "Osaka", "Estambul", "Dubái", "Karachi", "Ho Chi Minh", "Busan", "Hong Kong", "Calcuta"]],
  [2, "Países sin salida al mar",
    ["Suiza", "Austria", "Bolivia", "Paraguay", "Hungría", "República Checa", "Eslovaquia", "Mongolia", "Afganistán", "Nepal", "Etiopía", "Chad", "Mali", "Níger", "Kazajistán"],
    ["Chile", "Perú", "Croacia", "Polonia", "Rumanía", "Bulgaria", "Uruguay", "Eritrea", "Kenia", "Myanmar"]],
  [2, "Desiertos",
    ["Sahara", "Gobi", "Atacama", "Kalahari", "Namib", "Mojave", "Sonora", "Arábigo", "Thar", "Taklamakán", "Gran Desierto de Victoria", "Karakum", "Tabernas", "Kyzylkum", "Rub al-Jali"],
    ["Amazonas", "Serengeti", "Pampa", "Siberia", "Yucatán", "Borneo", "Congo", "Everglades", "Cerrado", "Los Llanos"]],
  [2, "Lagos",
    ["Titicaca", "Victoria", "Baikal", "Tanganica", "Malaui", "Superior", "Míchigan", "Hurón", "Ontario", "Erie", "Ladoga", "Constanza", "Lemán", "Como", "Garda"],
    ["Danubio", "Tajo", "Ebro", "Amazonas", "Orinoco", "Paraná", "Volga", "Mekong", "Zambeze", "Yukón"]],
  [2, "Capitales de África",
    ["El Cairo", "Rabat", "Argel", "Túnez", "Nairobi", "Adís Abeba", "Abuja", "Acra", "Dakar", "Luanda", "Maputo", "Kinsasa", "Jartum", "Trípoli", "Antananarivo"],
    ["Casablanca", "Marrakech", "Lagos", "Alejandría", "Johannesburgo", "Mombasa", "Tánger", "Durban", "Bengasi", "Fez"]],
  [2, "Países de Asia",
    ["Japón", "China", "India", "Corea del Sur", "Tailandia", "Vietnam", "Indonesia", "Filipinas", "Pakistán", "Irán", "Arabia Saudí", "Mongolia", "Nepal", "Malasia", "Afganistán"],
    ["Australia", "Nueva Zelanda", "Marruecos", "Madagascar", "Fiyi", "Papúa Nueva Guinea", "Somalia", "Etiopía", "Libia", "Ucrania"]],
  [2, "Países de Oceanía",
    ["Australia", "Nueva Zelanda", "Fiyi", "Papúa Nueva Guinea", "Samoa", "Tonga", "Vanuatu", "Islas Salomón", "Kiribati", "Tuvalu", "Nauru", "Palaos", "Micronesia", "Islas Marshall"],
    ["Indonesia", "Filipinas", "Malasia", "Japón", "Madagascar", "Sri Lanka", "Maldivas", "Mauricio", "Seychelles", "Hawái", "Singapur"]],
  [2, "Ciudades de Italia",
    ["Roma", "Milán", "Nápoles", "Turín", "Florencia", "Venecia", "Bolonia", "Génova", "Palermo", "Verona", "Pisa", "Siena", "Bari", "Trieste", "Cagliari"],
    ["Marsella", "Lyon", "Ginebra", "Lugano", "Liubliana", "Mónaco", "Innsbruck", "Salzburgo", "Split", "Valencia"]],

  // ---- Difícil ----
  [3, "Países por los que pasa el Danubio",
    ["Alemania", "Austria", "Eslovaquia", "Hungría", "Croacia", "Serbia", "Rumanía", "Bulgaria", "Moldavia", "Ucrania"],
    ["Polonia", "República Checa", "Suiza", "Francia", "Italia", "Eslovenia", "Bosnia", "Grecia", "Albania", "Macedonia del Norte", "Bélgica", "Países Bajos", "Rusia", "Bielorrusia", "Turquía"]],
  [3, "Capitales de provincia de España",
    ["Toledo", "Cáceres", "Huesca", "Teruel", "Soria", "Segovia", "Ávila", "Cuenca", "Zamora", "Palencia", "Lugo", "Ourense", "Jaén", "Huelva", "Castellón de la Plana"],
    ["Mérida", "Santiago de Compostela", "Vigo", "Gijón", "Jerez", "Cartagena", "Elche", "Marbella", "Talavera", "Ponferrada"]],
  [3, "Países que limitan con Brasil",
    ["Argentina", "Uruguay", "Paraguay", "Bolivia", "Perú", "Colombia", "Venezuela", "Guyana", "Surinam", "Francia"],
    ["Chile", "Ecuador", "México", "Panamá", "Costa Rica", "Cuba", "Honduras", "Guatemala", "Nicaragua", "El Salvador", "Belice", "Jamaica", "Haití", "Trinidad y Tobago", "República Dominicana"]],
  [3, "Capitales de países",
    ["Astaná", "Biskek", "Dusambé", "Asjabad", "Ereván", "Tiflis", "Bakú", "Chisináu", "Vilna", "Riga", "Tallin", "Liubliana", "Skopie", "Podgorica", "Tirana"],
    ["Almaty", "Samarcanda", "Odesa", "Tesalónica", "Split", "Cracovia", "Gdansk", "Batumi", "San Petersburgo", "Estambul"]],
  [3, "Países que cruza la línea del ecuador",
    ["Ecuador", "Colombia", "Brasil", "Gabón", "Santo Tomé y Príncipe", "República del Congo", "República Democrática del Congo", "Uganda", "Kenia", "Somalia", "Indonesia"],
    ["Guinea", "Venezuela", "Camerún", "Tanzania", "Etiopía", "Nigeria", "Malasia", "Singapur", "Filipinas", "Sri Lanka", "Papúa Nueva Guinea", "Ruanda", "Angola", "Panamá"]],
  [3, "Estados de Estados Unidos",
    ["California", "Texas", "Florida", "Alaska", "Hawái", "Nevada", "Arizona", "Ohio", "Georgia", "Montana", "Oregón", "Utah", "Maine", "Vermont", "Kentucky"],
    ["Quebec", "Ontario", "Alberta", "Yucatán", "Jalisco", "Puerto Rico", "Washington D. C.", "Guam", "Manitoba", "Nuevo León"]],
  [3, "Ríos de España",
    ["Ebro", "Tajo", "Duero", "Guadalquivir", "Guadiana", "Miño", "Júcar", "Segura", "Genil", "Sil", "Turia", "Nervión", "Pisuerga", "Llobregat", "Jarama"],
    ["Ródano", "Loira", "Sena", "Po", "Arno", "Mosela", "Mondego", "Tíber", "Rin", "Danubio"]],
  [3, "Montañas de más de 8000 metros",
    ["Everest", "K2", "Kangchenjunga", "Lhotse", "Makalu", "Cho Oyu", "Dhaulagiri", "Manaslu", "Nanga Parbat", "Annapurna", "Gasherbrum I", "Broad Peak", "Gasherbrum II", "Shisha Pangma"],
    ["Aconcagua", "Kilimanjaro", "Mont Blanc", "Denali", "Elbrus", "Vinson", "Cervino", "Teide", "Mulhacén", "Ama Dablam", "Chimborazo"]],
  [3, "Países con el español como lengua oficial",
    ["España", "México", "Colombia", "Argentina", "Perú", "Chile", "Cuba", "Bolivia", "Paraguay", "Guinea Ecuatorial", "Uruguay", "Nicaragua", "Costa Rica", "Panamá", "Honduras"],
    ["Brasil", "Filipinas", "Belice", "Portugal", "Andorra", "Marruecos", "Estados Unidos", "Haití", "Jamaica", "Guyana"]],
  [3, "Islas de Canarias o Baleares",
    ["Tenerife", "Gran Canaria", "Lanzarote", "Fuerteventura", "La Palma", "La Gomera", "El Hierro", "La Graciosa", "Mallorca", "Menorca", "Ibiza", "Formentera", "Cabrera", "Dragonera", "Isla de Lobos"],
    ["Madeira", "Azores", "Córcega", "Cerdeña", "Malta", "Sicilia", "Creta", "Islas Cíes", "Isla de Arosa", "Cabo Verde"]],
];
