// Campo de minas · Historia. [difficulty, prompt, right answers, mines] (see ./index.js).
export default [
  // ---- Fácil ----
  [1, "Presidentes de Estados Unidos",
    ["George Washington", "Abraham Lincoln", "Thomas Jefferson", "John F. Kennedy", "Barack Obama", "Donald Trump", "Joe Biden", "Ronald Reagan", "Richard Nixon", "Bill Clinton", "George W. Bush", "Franklin D. Roosevelt", "Jimmy Carter", "Theodore Roosevelt", "Eisenhower"],
    ["Benjamin Franklin", "Hillary Clinton", "Martin Luther King", "Al Gore", "Kamala Harris", "Alexander Hamilton", "Bernie Sanders", "Malcolm X", "John McCain", "Robert Kennedy"]],
  [1, "Exploradores y navegantes",
    ["Cristóbal Colón", "Magallanes", "Elcano", "Vasco da Gama", "Marco Polo", "Américo Vespucio", "James Cook", "Amundsen", "Bartolomé Díaz", "Núñez de Balboa", "Francis Drake", "Henry Hudson", "Abel Tasman", "Ibn Battuta", "Shackleton"],
    ["Napoleón", "Julio César", "Leonardo da Vinci", "Shakespeare", "Cervantes", "Galileo", "Mozart", "Gandhi", "Isabel la Católica", "Carlomagno"]],
  [1, "Reyes de España",
    ["Carlos I", "Felipe II", "Carlos III", "Felipe VI", "Juan Carlos I", "Alfonso XIII", "Felipe V", "Fernando VII", "Isabel II", "Carlos IV", "Alfonso XII", "Felipe IV", "Carlos II", "Amadeo I", "Fernando VI"],
    ["Luis XIV", "Enrique VIII", "Napoleón", "Carlomagno", "Isabel I de Inglaterra", "Ricardo Corazón de León", "Pedro el Grande", "Luis XVI", "Jorge III", "Federico el Grande"]],
  [1, "Personajes de la antigua Roma",
    ["Julio César", "Augusto", "Nerón", "Cicerón", "Espartaco", "Marco Antonio", "Calígula", "Trajano", "Adriano", "Pompeyo", "Bruto", "Rómulo", "Séneca", "Virgilio", "Escipión"],
    ["Alejandro Magno", "Aníbal", "Cleopatra", "Sócrates", "Platón", "Napoleón", "Carlomagno", "Atila", "Pericles", "Leónidas"]],
  [1, "Dioses griegos",
    ["Zeus", "Hera", "Poseidón", "Atenea", "Apolo", "Artemisa", "Ares", "Afrodita", "Hermes", "Hefesto", "Deméter", "Dioniso", "Hades", "Hestia", "Perséfone"],
    ["Júpiter", "Marte", "Venus", "Odín", "Thor", "Ra", "Osiris", "Anubis", "Neptuno", "Quetzalcóatl"]],
  [1, "Líderes de la Segunda Guerra Mundial",
    ["Churchill", "Roosevelt", "Stalin", "Hitler", "Mussolini", "De Gaulle", "Hirohito", "Eisenhower", "Montgomery", "Rommel", "Truman", "Chiang Kai-shek", "Patton", "Zhúkov", "MacArthur"],
    ["Napoleón", "Lenin", "Bismarck", "Fidel Castro", "Gorbachov", "Káiser Guillermo II", "Thatcher", "Lincoln", "Che Guevara", "Mandela"]],
  [1, "Cosas de la Edad Media",
    ["Castillo", "Caballero", "Feudalismo", "Cruzadas", "Peste negra", "Vikingos", "Monasterio", "Juglar", "Gremio", "Siervo", "Torneo", "Catedral gótica", "Carlomagno", "Reconquista", "Armadura"],
    ["Máquina de vapor", "Revolución francesa", "Pirámides de Guiza", "Ferrocarril", "Telégrafo", "Gladiador", "Faraón", "Revolución industrial", "Napoleón", "Mamut"]],
  [1, "Cosas del antiguo Egipto",
    ["Pirámide", "Faraón", "Momia", "Esfinge", "Jeroglífico", "Papiro", "Nilo", "Escarabajo sagrado", "Sarcófago", "Obelisco", "Ra", "Anubis", "Cleopatra", "Tutankamón", "Piedra de Rosetta"],
    ["Coliseo", "Partenón", "Acrópolis", "Gladiador", "Samurái", "Vikingo", "Zeus", "Legionario", "Stonehenge", "Gran Muralla"]],
  [1, "Imperios que existieron de verdad",
    ["Imperio romano", "Imperio otomano", "Imperio mongol", "Imperio británico", "Imperio persa", "Imperio inca", "Imperio azteca", "Imperio bizantino", "Imperio español", "Imperio austrohúngaro", "Imperio ruso", "Imperio carolingio", "Imperio japonés", "Imperio portugués", "Imperio chino"],
    ["Imperio Galáctico", "Imperio Klingon", "Reino de Gondor", "Reino de Wakanda", "Unión Europea", "OTAN", "ONU", "Liga Hanseática", "República de Weimar", "Mercosur"]],
  [1, "Personajes del siglo XX",
    ["Gandhi", "Einstein", "Hitler", "Churchill", "Mandela", "Che Guevara", "Martin Luther King", "Picasso", "Kennedy", "Gorbachov", "Fidel Castro", "Lenin", "Mao Zedong", "Juan Pablo II", "Franco"],
    ["Napoleón", "Colón", "Shakespeare", "Cervantes", "Leonardo da Vinci", "Julio César", "Mozart", "Beethoven", "Lincoln", "Simón Bolívar"]],

  // ---- Media ----
  [2, "Emperadores romanos",
    ["Augusto", "Tiberio", "Calígula", "Claudio", "Nerón", "Vespasiano", "Tito", "Domiciano", "Trajano", "Adriano", "Marco Aurelio", "Cómodo", "Caracalla", "Diocleciano", "Constantino"],
    ["Julio César", "Cicerón", "Espartaco", "Aníbal", "Pompeyo", "Marco Antonio", "Bruto", "Atila", "Cleopatra", "Alejandro Magno"]],
  [2, "Faraones de Egipto",
    ["Tutankamón", "Ramsés II", "Cleopatra", "Keops", "Kefrén", "Micerinos", "Hatshepsut", "Akenatón", "Tutmosis III", "Amenofis III", "Seti I", "Zoser", "Narmer", "Ptolomeo I", "Ramsés III"],
    ["Hammurabi", "Nabucodonosor", "Darío I", "Jerjes", "Ciro el Grande", "Gilgamesh", "Asurbanipal", "Saladino", "Herodes", "Salomón"]],
  [2, "Civilizaciones precolombinas de América",
    ["Mayas", "Aztecas", "Incas", "Olmecas", "Toltecas", "Zapotecas", "Mixtecas", "Chimú", "Nazca", "Moche", "Teotihuacanos", "Tiahuanaco", "Muiscas", "Taínos", "Chavín"],
    ["Egipcios", "Sumerios", "Fenicios", "Celtas", "Persas", "Etruscos", "Hititas", "Mongoles", "Babilonios", "Escitas"]],
  [2, "Países aliados en la Segunda Guerra Mundial",
    ["Reino Unido", "Estados Unidos", "Unión Soviética", "Francia", "China", "Canadá", "Australia", "Polonia", "Brasil", "México", "Países Bajos", "Bélgica", "Noruega", "Grecia", "Nueva Zelanda", "Sudáfrica"],
    ["Alemania", "Japón", "Hungría", "Suiza", "Suecia", "España", "Portugal", "Irlanda", "Eslovaquia"]],
  [2, "Batallas famosas",
    ["Waterloo", "Trafalgar", "Hastings", "Termópilas", "Stalingrado", "Gettysburg", "Lepanto", "Maratón", "Austerlitz", "Normandía", "Verdún", "Bailén", "Midway", "Las Navas de Tolosa", "Covadonga"],
    ["Versalles", "Tordesillas", "Westfalia", "Yalta", "Potsdam", "Utrecht", "Múnich", "Maastricht", "Teherán", "Ginebra"]],
  [2, "Mujeres que gobernaron un país",
    ["Isabel I de Inglaterra", "Cleopatra", "Catalina la Grande", "Isabel la Católica", "Reina Victoria", "Margaret Thatcher", "Indira Gandhi", "Angela Merkel", "Golda Meir", "Benazir Bhutto", "Isabel II", "Hatshepsut", "María Teresa de Austria", "Michelle Bachelet", "Cristina Kirchner"],
    ["Marie Curie", "Juana de Arco", "Frida Kahlo", "Eva Perón", "Hillary Clinton", "Rosa Parks", "Ana Frank", "Florence Nightingale", "Jackie Kennedy", "Coco Chanel"]],
  [2, "Papas de la Iglesia católica",
    ["Juan Pablo II", "Benedicto XVI", "Francisco", "León XIV", "Pablo VI", "Juan XXIII", "Pío XII", "Juan Pablo I", "Gregorio Magno", "Inocencio III", "Alejandro VI", "Urbano II", "Pío IX", "Julio II", "León X"],
    ["Martín Lutero", "Calvino", "Tomás de Aquino", "San Agustín", "Francisco de Asís", "Ignacio de Loyola", "Richelieu", "Rasputín", "Savonarola", "Teresa de Calcuta"]],
  [2, "Reyes de Francia",
    ["Luis XIV", "Luis XVI", "Luis XIII", "Luis XV", "Enrique IV", "Francisco I", "Carlos X", "Luis Felipe I", "Luis IX", "Hugo Capeto", "Clodoveo", "Carlos VII", "Felipe Augusto", "Luis XI", "Luis XVIII"],
    ["Enrique VIII", "Ricardo Corazón de León", "Isabel la Católica", "Felipe II", "Fernando el Católico", "Guillermo el Conquistador", "Jorge III", "Federico el Grande", "Pedro el Grande", "Alfonso X"]],
  [2, "Tratados de paz y acuerdos",
    ["Versalles", "Tordesillas", "Westfalia", "Utrecht", "Maastricht", "Lisboa", "Brest-Litovsk", "Nankín", "Guadalupe Hidalgo", "Tilsit", "Trianón", "Campo Formio", "Alcaçovas", "Pirineos", "Ryswick"],
    ["Waterloo", "Trafalgar", "Stalingrado", "Lepanto", "Austerlitz", "Hastings", "Gettysburg", "Verdún", "Bailén", "Termópilas"]],
  [2, "Dinastías",
    ["Ming", "Tang", "Han", "Qing", "Song", "Yuan", "Habsburgo", "Borbón", "Tudor", "Estuardo", "Romanov", "Windsor", "Trastámara", "Capeto", "Plantagenet"],
    ["Gótico", "Románico", "Barroco", "Renacimiento", "Ilustración", "Neolítico", "Paleolítico", "Jurásico", "Cámbrico", "Neoclásico"]],

  // ---- Difícil ----
  [3, "Presidentes del Gobierno de España",
    ["Adolfo Suárez", "Leopoldo Calvo-Sotelo", "Felipe González", "José María Aznar", "Zapatero", "Mariano Rajoy", "Pedro Sánchez", "Manuel Azaña", "Juan Negrín", "Largo Caballero", "Alejandro Lerroux", "Casares Quiroga", "Carrero Blanco", "Arias Navarro", "Cánovas del Castillo"],
    ["Manuel Fraga", "Santiago Carrillo", "Alfonso Guerra", "Rodrigo Rato", "Pérez Rubalcaba", "Julio Anguita", "Pablo Iglesias", "Albert Rivera", "Sáenz de Santamaría", "Mayor Zaragoza"]],
  [3, "Conquistadores españoles",
    ["Hernán Cortés", "Francisco Pizarro", "Diego de Almagro", "Pedro de Valdivia", "Núñez de Balboa", "Ponce de León", "Hernando de Soto", "Pedro de Alvarado", "Jiménez de Quesada", "Francisco de Orellana", "Cabeza de Vaca", "Vázquez de Coronado", "Pedro de Mendoza", "Lope de Aguirre", "Juan de Garay"],
    ["Vasco da Gama", "Álvares Cabral", "Jacques Cartier", "Samuel de Champlain", "Henry Hudson", "Francis Drake", "Walter Raleigh", "Américo Vespucio", "Juan Caboto", "Bartolomeu Dias"]],
  [3, "Personajes de la Revolución francesa",
    ["Robespierre", "Danton", "Marat", "Saint-Just", "Mirabeau", "Lafayette", "Sieyès", "Camille Desmoulins", "Charlotte Corday", "Luis XVI", "María Antonieta", "Brissot", "Hébert", "Condorcet", "Olympe de Gouges"],
    ["Metternich", "Bismarck", "Garibaldi", "Mazzini", "Wellington", "Nelson", "Cromwell", "Lenin", "Trotski", "Simón Bolívar"]],
  [3, "Batallas de las guerras napoleónicas",
    ["Austerlitz", "Waterloo", "Trafalgar", "Jena", "Wagram", "Borodino", "Leipzig", "Eylau", "Friedland", "Bailén", "Smolensk", "Ulm", "Arapiles", "Vitoria", "Aspern-Essling"],
    ["Somme", "Verdún", "Gettysburg", "Lepanto", "Pavía", "Rocroi", "Stalingrado", "El Alamein", "Hastings", "Azincourt"]],
  [3, "Pueblos prerromanos de la península ibérica",
    ["Íberos", "Celtas", "Celtíberos", "Lusitanos", "Vetones", "Vacceos", "Astures", "Cántabros", "Galaicos", "Vascones", "Turdetanos", "Ilergetes", "Carpetanos", "Oretanos", "Bastetanos"],
    ["Visigodos", "Suevos", "Vándalos", "Alanos", "Árabes", "Bereberes", "Romanos", "Normandos", "Bizantinos", "Almohades"]],
  [3, "Guerras del siglo XIX",
    ["Guerra de Crimea", "Guerra franco-prusiana", "Guerra de Secesión", "Guerra del Opio", "Guerra de la Independencia española", "Guerras carlistas", "Guerra de los Bóeres", "Guerra hispano-estadounidense", "Guerra del Pacífico", "Guerra de la Triple Alianza", "Guerra México-Estados Unidos", "Guerra anglo-zulú", "Guerra austro-prusiana", "Guerra de los Diez Años", "Guerra de África"],
    ["Guerra de los Cien Años", "Guerra de los Treinta Años", "Guerra de Sucesión española", "Guerra de los Siete Años", "Guerra de Vietnam", "Guerra de Corea", "Guerra de las Malvinas", "Guerra del Golfo", "Guerra de las Dos Rosas", "Guerra Civil española"]],
  [3, "Padres fundadores de Estados Unidos",
    ["George Washington", "Thomas Jefferson", "Benjamin Franklin", "John Adams", "James Madison", "Alexander Hamilton", "John Jay", "Samuel Adams", "John Hancock", "Gouverneur Morris", "Roger Sherman", "Patrick Henry", "Thomas Paine", "George Mason"],
    ["Abraham Lincoln", "Andrew Jackson", "Ulysses S. Grant", "Robert E. Lee", "Theodore Roosevelt", "Woodrow Wilson", "Daniel Boone", "Davy Crockett", "Buffalo Bill", "Frederick Douglass", "Jefferson Davis"]],
  [3, "Dioses nórdicos",
    ["Odín", "Thor", "Loki", "Freya", "Frigg", "Balder", "Tyr", "Heimdal", "Njord", "Frey", "Idún", "Bragi", "Hel", "Vidar", "Ull"],
    ["Zeus", "Ra", "Osiris", "Marte", "Ganesha", "Quetzalcóatl", "Baal", "Mitra", "Anubis", "Shiva"]],
  [3, "Nombres romanos de ciudades de España",
    ["Caesaraugusta", "Emerita Augusta", "Tarraco", "Hispalis", "Corduba", "Toletum", "Barcino", "Gades", "Carthago Nova", "Valentia", "Legio", "Asturica Augusta", "Lucus Augusti", "Malaca", "Pompaelo"],
    ["Lutetia", "Londinium", "Olisipo", "Massalia", "Byzantium", "Mediolanum", "Colonia Agrippina", "Lugdunum", "Aquincum", "Augusta Treverorum"]],
  [3, "Ocurrió en el siglo XV",
    ["Cae Constantinopla", "Colón llega a América", "Toma de Granada", "Imprenta de Gutenberg", "Muere Juana de Arco", "Fin de la guerra de los Cien Años", "Tratado de Tordesillas", "Vasco da Gama llega a la India", "Boda de los Reyes Católicos", "Gramática de Nebrija", "Guerra de las Dos Rosas", "Nace la Inquisición española", "Batalla de Azincourt", "Expulsión de los judíos de España", "Concilio de Constanza"],
    ["Muere Carlomagno", "Reforma de Lutero", "Primera vuelta al mundo", "Conquista de México", "Batalla de Lepanto", "Armada Invencible", "Peste negra", "Batalla de Hastings", "Primera cruzada", "Revolución francesa"]],
];
