// Campo de minas · Literatura. [difficulty, prompt, right answers, mines] (see ./index.js).
export default [
  // ---- Fácil ----
  [1, "Obras de Shakespeare",
    ["Hamlet", "Macbeth", "Otelo", "Romeo y Julieta", "El rey Lear", "La tempestad", "El mercader de Venecia", "Sueño de una noche de verano", "Julio César", "Ricardo III", "Mucho ruido y pocas nueces", "La fierecilla domada", "Noche de reyes", "Antonio y Cleopatra", "Coriolano"],
    ["Don Quijote", "Fausto", "La Celestina", "El Lazarillo", "Tartufo", "Edipo rey", "Orgullo y prejuicio", "Cyrano de Bergerac", "La vida es sueño", "Drácula"]],
  [1, "Personajes de Harry Potter",
    ["Harry", "Hermione", "Ron", "Dumbledore", "Snape", "Voldemort", "Hagrid", "Draco Malfoy", "Sirius Black", "Neville", "Luna Lovegood", "Dobby", "McGonagall", "Ginny", "Bellatrix"],
    ["Gandalf", "Frodo", "Aragorn", "Legolas", "Aslan", "Percy Jackson", "Katniss", "Bilbo", "Sauron", "Edward Cullen"]],
  [1, "Escritores españoles",
    ["Cervantes", "Lope de Vega", "Quevedo", "Góngora", "Calderón de la Barca", "García Lorca", "Antonio Machado", "Unamuno", "Pérez Galdós", "Bécquer", "Rosalía de Castro", "Pérez-Reverte", "Miguel Delibes", "Camilo José Cela", "Juan Ramón Jiménez"],
    ["García Márquez", "Pablo Neruda", "Borges", "Julio Cortázar", "Isabel Allende", "Octavio Paz", "Rubén Darío", "Gabriela Mistral", "Juan Rulfo", "Mario Benedetti"]],
  [1, "Escritores latinoamericanos",
    ["García Márquez", "Pablo Neruda", "Borges", "Julio Cortázar", "Isabel Allende", "Octavio Paz", "Rubén Darío", "Gabriela Mistral", "Juan Rulfo", "Mario Benedetti", "Vargas Llosa", "Carlos Fuentes", "Alfonsina Storni", "José Martí", "Horacio Quiroga"],
    ["Cervantes", "Lope de Vega", "Quevedo", "García Lorca", "Antonio Machado", "Unamuno", "Pérez Galdós", "Bécquer", "Miguel Delibes", "Camilo José Cela"]],
  [1, "Cuentos clásicos infantiles",
    ["Caperucita Roja", "Blancanieves", "La Cenicienta", "Hansel y Gretel", "Pulgarcito", "El gato con botas", "La bella durmiente", "Los tres cerditos", "Ricitos de Oro", "El patito feo", "La sirenita", "Rapunzel", "Pinocho", "El soldadito de plomo", "Juan y las habichuelas mágicas"],
    ["Harry Potter", "Los juegos del hambre", "Crepúsculo", "El código Da Vinci", "Cien años de soledad", "1984", "Drácula", "Frankenstein", "El Señor de los Anillos", "La Odisea"]],
  [1, "Personajes de El Señor de los Anillos",
    ["Frodo", "Sam", "Gandalf", "Aragorn", "Legolas", "Gimli", "Gollum", "Sauron", "Boromir", "Saruman", "Pippin", "Merry", "Galadriel", "Elrond", "Arwen"],
    ["Dumbledore", "Voldemort", "Aslan", "Hermione", "Darth Vader", "Jon Nieve", "Daenerys", "Harry Potter", "Tyrion", "Bastian"]],
  [1, "Géneros literarios",
    ["Novela", "Poesía", "Teatro", "Ensayo", "Cuento", "Fábula", "Epopeya", "Biografía", "Oda", "Tragedia", "Comedia", "Crónica", "Leyenda", "Elegía", "Sátira"],
    ["Sinfonía", "Acuarela", "Óleo", "Escultura", "Vals", "Tango", "Fresco", "Mosaico", "Sonata", "Grabado"]],
  [1, "Autores de libros infantiles y juveniles",
    ["Roald Dahl", "J. K. Rowling", "Gloria Fuertes", "Andersen", "Hermanos Grimm", "Charles Perrault", "Lewis Carroll", "Enid Blyton", "Michael Ende", "Astrid Lindgren", "Saint-Exupéry", "Elvira Lindo", "Laura Gallego", "Beatrix Potter", "R. L. Stine"],
    ["Stephen King", "Kafka", "Dostoievski", "Nietzsche", "Marcel Proust", "Bukowski", "Henry Miller", "Cormac McCarthy", "Sartre", "Albert Camus"]],
  [1, "Personajes de la literatura española",
    ["Don Quijote", "Sancho Panza", "Lazarillo de Tormes", "La Celestina", "Don Juan Tenorio", "Segismundo", "Bernarda Alba", "Platero", "Dulcinea", "Rocinante", "El Cid", "Fortunata", "Pascual Duarte", "Max Estrella", "Yerma"],
    ["Hamlet", "Romeo", "Fausto", "Ana Karenina", "Madame Bovary", "Sherlock Holmes", "Oliver Twist", "Gregor Samsa", "Jean Valjean", "Dorian Gray"]],
  [1, "Partes de un libro",
    ["Portada", "Contraportada", "Índice", "Capítulo", "Prólogo", "Epílogo", "Lomo", "Solapa", "Página", "Párrafo", "Dedicatoria", "Glosario", "Bibliografía", "Colofón", "Sobrecubierta"],
    ["Teclado", "Pantalla", "Rueda", "Volante", "Pedal", "Bisagra", "Cremallera", "Suela", "Manillar", "Tecla"]],

  // ---- Media ----
  [2, "Obras de Miguel de Cervantes",
    ["Don Quijote", "Novelas ejemplares", "La Galatea", "Persiles y Sigismunda", "Rinconete y Cortadillo", "El coloquio de los perros", "La gitanilla", "El licenciado Vidriera", "La Numancia", "Viaje del Parnaso", "El retablo de las maravillas", "El celoso extremeño", "La ilustre fregona", "La española inglesa", "El casamiento engañoso"],
    ["Lazarillo de Tormes", "La Celestina", "La vida es sueño", "Fuenteovejuna", "El Buscón", "El burlador de Sevilla", "Soledades", "Guzmán de Alfarache", "El perro del hortelano", "Don Juan Tenorio"]],
  [2, "Novelas de Julio Verne",
    ["La vuelta al mundo en 80 días", "20.000 leguas de viaje submarino", "Viaje al centro de la Tierra", "De la Tierra a la Luna", "Miguel Strogoff", "La isla misteriosa", "Cinco semanas en globo", "Los hijos del capitán Grant", "Un capitán de quince años", "Robur el conquistador", "El faro del fin del mundo", "Alrededor de la Luna", "Matías Sandorf", "Escuela de Robinsones", "El rayo verde"],
    ["La máquina del tiempo", "La guerra de los mundos", "El hombre invisible", "Robinson Crusoe", "La isla del tesoro", "Los viajes de Gulliver", "Moby Dick", "Frankenstein", "Drácula", "Los tres mosqueteros"]],
  [2, "Detectives de novela",
    ["Sherlock Holmes", "Hércules Poirot", "Miss Marple", "Philip Marlowe", "Sam Spade", "Padre Brown", "Auguste Dupin", "Maigret", "Pepe Carvalho", "Kurt Wallander", "Nero Wolfe", "Ellery Queen", "Montalbano", "Harry Hole", "Mike Hammer"],
    ["Moriarty", "Drácula", "Frankenstein", "Dorian Gray", "Don Juan Tenorio", "Robinson Crusoe", "Oliver Twist", "Tom Sawyer", "Ana Karenina", "Madame Bovary"]],
  [2, "Personajes de Alicia en el país de las maravillas",
    ["Alicia", "Conejo Blanco", "Sombrerero Loco", "Gato de Cheshire", "Reina de Corazones", "Liebre de Marzo", "Oruga", "Lirón", "Falsa Tortuga", "Duquesa", "Rey de Corazones", "Grifo", "Dodo", "Sota de Corazones", "Bill la lagartija"],
    ["Peter Pan", "Campanilla", "Capitán Garfio", "Wendy", "Pinocho", "Pepito Grillo", "Dorothy", "Hombre de Hojalata", "Espantapájaros", "Mago de Oz"]],
  [2, "Libros de la Biblia",
    ["Génesis", "Éxodo", "Levítico", "Números", "Deuteronomio", "Salmos", "Proverbios", "Isaías", "Job", "Rut", "Apocalipsis", "Evangelio de Mateo", "Evangelio de Marcos", "Evangelio de Lucas", "Evangelio de Juan"],
    ["Corán", "Odisea", "Ilíada", "Eneida", "Talmud", "Mahabharata", "Popol Vuh", "Gilgamesh", "Bhagavad Gita", "Upanishads"]],
  [2, "Libros de Gabriel García Márquez",
    ["Cien años de soledad", "El amor en los tiempos del cólera", "Crónica de una muerte anunciada", "El coronel no tiene quien le escriba", "El otoño del patriarca", "Del amor y otros demonios", "La hojarasca", "El general en su laberinto", "Noticia de un secuestro", "Relato de un náufrago", "La mala hora", "Doce cuentos peregrinos", "Vivir para contarla", "En agosto nos vemos"],
    ["Rayuela", "La casa de los espíritus", "Pedro Páramo", "La ciudad y los perros", "Ficciones", "El túnel", "Como agua para chocolate", "Aura", "La tregua", "Los detectives salvajes", "Paula"]],
  [2, "Obras de Federico García Lorca",
    ["Bodas de sangre", "Yerma", "La casa de Bernarda Alba", "Romancero gitano", "Poeta en Nueva York", "Mariana Pineda", "Doña Rosita la soltera", "Así que pasen cinco años", "El público", "Llanto por Ignacio Sánchez Mejías", "Diván del Tamarit", "Libro de poemas", "Poema del cante jondo", "La zapatera prodigiosa", "El maleficio de la mariposa"],
    ["Campos de Castilla", "Platero y yo", "La vida es sueño", "Luces de bohemia", "Fuenteovejuna", "El sí de las niñas", "Don Juan Tenorio", "Rimas", "Niebla", "Historia de una escalera"]],
  [2, "Personajes de Don Quijote",
    ["Don Quijote", "Sancho Panza", "Dulcinea", "Rocinante", "Rucio", "Sansón Carrasco", "Maritornes", "Ginés de Pasamonte", "Teresa Panza", "Cide Hamete Benengeli", "El cura Pero Pérez", "Maese Nicolás", "Cardenio", "Dorotea", "Altisidora"],
    ["Lazarillo", "Celestina", "Calisto", "Melibea", "Segismundo", "Don Juan Tenorio", "Doña Inés", "El Cid", "Platero", "Bernarda Alba"]],
  [2, "Escritores de terror",
    ["Stephen King", "Edgar Allan Poe", "H. P. Lovecraft", "Bram Stoker", "Mary Shelley", "Anne Rice", "Clive Barker", "Shirley Jackson", "Dean Koontz", "Peter Straub", "Ira Levin", "William Peter Blatty", "Sheridan Le Fanu", "Ann Radcliffe", "Horace Walpole"],
    ["Jane Austen", "Tolkien", "J. K. Rowling", "García Márquez", "Cervantes", "Julio Verne", "Mark Twain", "Tolstói", "Paulo Coelho", "Isabel Allende"]],
  [2, "Novelas de ciencia ficción o distopías",
    ["1984", "Un mundo feliz", "Fahrenheit 451", "Dune", "Fundación", "Yo, robot", "La guerra de los mundos", "La máquina del tiempo", "Los juegos del hambre", "El cuento de la criada", "Neuromante", "¿Sueñan los androides con ovejas eléctricas?", "Solaris", "La naranja mecánica", "Crónicas marcianas"],
    ["Orgullo y prejuicio", "Cien años de soledad", "Don Quijote", "Madame Bovary", "Moby Dick", "Los miserables", "Ana Karenina", "El gran Gatsby", "Mujercitas", "Cumbres borrascosas"]],

  // ---- Difícil ----
  [3, "Ganadores del Nobel de Literatura",
    ["García Márquez", "Pablo Neruda", "Vargas Llosa", "Octavio Paz", "Gabriela Mistral", "Camilo José Cela", "Juan Ramón Jiménez", "Vicente Aleixandre", "Jacinto Benavente", "José Echegaray", "Hemingway", "Albert Camus", "Bob Dylan", "Kazuo Ishiguro", "Orhan Pamuk"],
    ["Borges", "Julio Cortázar", "Tolstói", "James Joyce", "Franz Kafka", "Virginia Woolf", "Marcel Proust", "García Lorca", "Philip Roth", "Jane Austen"]],
  [3, "Escritores nacidos en Inglaterra",
    ["Shakespeare", "Charles Dickens", "Jane Austen", "J. K. Rowling", "Agatha Christie", "Virginia Woolf", "Lewis Carroll", "Mary Shelley", "Charlotte Brontë", "Thomas Hardy", "John Milton", "Chaucer", "Ian McEwan", "Daniel Defoe", "Lord Byron"],
    ["Oscar Wilde", "Conan Doyle", "R. L. Stevenson", "James Joyce", "Bernard Shaw", "Mark Twain", "Edgar Allan Poe", "Walter Scott", "C. S. Lewis", "Samuel Beckett"]],
  [3, "Poetas de la Generación del 27",
    ["García Lorca", "Rafael Alberti", "Luis Cernuda", "Jorge Guillén", "Pedro Salinas", "Vicente Aleixandre", "Dámaso Alonso", "Gerardo Diego", "Emilio Prados", "Manuel Altolaguirre", "Concha Méndez", "Ernestina de Champourcín"],
    ["Antonio Machado", "Unamuno", "Juan Ramón Jiménez", "Rubén Darío", "Bécquer", "Espronceda", "Garcilaso", "Quevedo", "Góngora", "Rosalía de Castro", "Valle-Inclán", "Blas de Otero", "Gloria Fuertes"]],
  [3, "Novelas de Charles Dickens",
    ["Oliver Twist", "David Copperfield", "Grandes esperanzas", "Canción de Navidad", "Historia de dos ciudades", "Tiempos difíciles", "Casa desolada", "Los papeles del Club Pickwick", "Nicholas Nickleby", "La tienda de antigüedades", "La pequeña Dorrit", "Nuestro común amigo", "Barnaby Rudge", "Martin Chuzzlewit", "El misterio de Edwin Drood"],
    ["Jane Eyre", "Cumbres borrascosas", "Orgullo y prejuicio", "Frankenstein", "Drácula", "El retrato de Dorian Gray", "Ivanhoe", "La feria de las vanidades", "Middlemarch", "Tess de los d'Urberville"]],
  [3, "Personajes de la Ilíada o la Odisea",
    ["Aquiles", "Héctor", "Ulises", "Penélope", "Telémaco", "Agamenón", "Menelao", "Helena", "Paris", "Príamo", "Patroclo", "Áyax", "Polifemo", "Calipso", "Circe"],
    ["Rómulo", "Remo", "Dido", "Medea", "Antígona", "Prometeo", "Pandora", "Narciso", "Orfeo", "Ícaro"]],
  [3, "Obras de Benito Pérez Galdós",
    ["Fortunata y Jacinta", "Marianela", "Doña Perfecta", "Misericordia", "Tristana", "Episodios nacionales", "Trafalgar", "El abuelo", "Miau", "La desheredada", "Gloria", "Electra", "Torquemada en la hoguera", "Nazarín", "El amigo Manso"],
    ["La Regenta", "Los pazos de Ulloa", "Pepita Jiménez", "El sombrero de tres picos", "La barraca", "Niebla", "San Manuel Bueno, mártir", "Peñas arriba", "La busca", "Cañas y barro"]],
  [3, "Escritores conocidos por un seudónimo",
    ["George Orwell", "Mark Twain", "Lewis Carroll", "Pablo Neruda", "Gabriela Mistral", "Voltaire", "Molière", "Stendhal", "George Eliot", "Azorín", "Clarín", "Fernán Caballero", "Rubén Darío", "Novalis", "Máximo Gorki"],
    ["Charles Dickens", "Jane Austen", "Miguel de Cervantes", "García Lorca", "García Márquez", "Julio Cortázar", "Isabel Allende", "Ernest Hemingway", "Franz Kafka", "Oscar Wilde"]],
  [3, "Obras del Siglo de Oro español",
    ["La vida es sueño", "Fuenteovejuna", "El burlador de Sevilla", "El perro del hortelano", "Don Quijote", "Lazarillo de Tormes", "El Buscón", "Soledades", "El alcalde de Zalamea", "La dama boba", "Novelas ejemplares", "El caballero de Olmedo", "Guzmán de Alfarache", "Los sueños", "Noche oscura del alma"],
    ["Cantar de mio Cid", "El conde Lucanor", "Libro de buen amor", "Don Juan Tenorio", "Rimas", "La Regenta", "Bodas de sangre", "Luces de bohemia", "Platero y yo", "Campos de Castilla"]],
  [3, "Obras de autores rusos",
    ["Guerra y paz", "Ana Karenina", "Crimen y castigo", "Los hermanos Karamázov", "El idiota", "Doctor Zhivago", "Almas muertas", "El maestro y Margarita", "Archipiélago Gulag", "Padres e hijos", "Eugenio Oneguin", "La muerte de Iván Ilich", "El jardín de los cerezos", "Oblómov", "El capote"],
    ["Madame Bovary", "Los miserables", "El proceso", "La metamorfosis", "Ulises", "En busca del tiempo perdido", "Werther", "El extranjero", "Las uvas de la ira", "Rojo y negro"]],
  [3, "Obras de Edgar Allan Poe",
    ["El cuervo", "El gato negro", "La caída de la casa Usher", "El corazón delator", "Los crímenes de la calle Morgue", "El pozo y el péndulo", "La máscara de la muerte roja", "El escarabajo de oro", "La carta robada", "Annabel Lee", "El barril de amontillado", "Berenice", "Ligeia", "Arthur Gordon Pym", "El retrato oval"],
    ["Drácula", "Frankenstein", "Dr. Jekyll y Mr. Hyde", "La llamada de Cthulhu", "Carrie", "El fantasma de la ópera", "Otra vuelta de tuerca", "Carmilla", "El monje", "Entrevista con el vampiro"]],
];
