// Campo de minas · Música. [difficulty, prompt, right answers, mines] (see ./index.js).
export default [
  // ---- Fácil ----
  [1, "Instrumentos de cuerda",
    ["Guitarra", "Violín", "Violonchelo", "Contrabajo", "Arpa", "Viola", "Ukelele", "Bajo eléctrico", "Banjo", "Mandolina", "Laúd", "Sitar", "Bandurria", "Charango", "Lira"],
    ["Trompeta", "Flauta", "Tambor", "Saxofón", "Clarinete", "Trombón", "Tuba", "Xilófono", "Armónica", "Gaita"]],
  [1, "Instrumentos de viento",
    ["Flauta", "Trompeta", "Saxofón", "Clarinete", "Oboe", "Fagot", "Trombón", "Tuba", "Trompa", "Armónica", "Gaita", "Flauta dulce", "Corneta", "Didgeridoo", "Ocarina"],
    ["Violín", "Guitarra", "Arpa", "Batería", "Xilófono", "Timbal", "Pandereta", "Contrabajo", "Castañuelas", "Triángulo"]],
  [1, "Grupos de música",
    ["The Beatles", "Queen", "ABBA", "Coldplay", "U2", "Metallica", "Nirvana", "The Rolling Stones", "Maná", "Mecano", "La Oreja de Van Gogh", "Pink Floyd", "BTS", "Imagine Dragons", "Maroon 5"],
    ["Madonna", "Shakira", "Michael Jackson", "Elvis Presley", "Bad Bunny", "Taylor Swift", "Rosalía", "Ed Sheeran", "Adele", "Rihanna"]],
  [1, "Cantantes de reguetón",
    ["Bad Bunny", "Daddy Yankee", "J Balvin", "Ozuna", "Maluma", "Karol G", "Anuel AA", "Nicky Jam", "Don Omar", "Wisin", "Farruko", "Rauw Alejandro", "Myke Towers", "Feid", "Sech"],
    ["Adele", "Ed Sheeran", "Coldplay", "Bruce Springsteen", "Taylor Swift", "Metallica", "Elton John", "Bob Dylan", "Frank Sinatra", "Mozart"]],
  [1, "Compositores de música clásica",
    ["Mozart", "Beethoven", "Bach", "Vivaldi", "Chopin", "Tchaikovsky", "Haydn", "Schubert", "Brahms", "Verdi", "Wagner", "Handel", "Debussy", "Liszt", "Rossini"],
    ["Elvis Presley", "Freddie Mercury", "Michael Jackson", "Bob Marley", "Frank Sinatra", "Kurt Cobain", "David Bowie", "Elton John", "Paul McCartney", "John Lennon"]],
  [1, "Géneros musicales",
    ["Rock", "Pop", "Jazz", "Blues", "Reguetón", "Salsa", "Flamenco", "Tango", "Reggae", "Hip hop", "Heavy metal", "Cumbia", "Bachata", "Country", "Techno"],
    ["Acuarela", "Soneto", "Haiku", "Óleo", "Fresco", "Mosaico", "Novela", "Fábula", "Origami", "Grafiti"]],
  [1, "Instrumentos de percusión",
    ["Tambor", "Batería", "Bombo", "Platillos", "Xilófono", "Timbal", "Pandereta", "Castañuelas", "Maracas", "Bongó", "Cajón", "Triángulo", "Marimba", "Güiro", "Gong"],
    ["Violín", "Flauta", "Trompeta", "Guitarra", "Arpa", "Clarinete", "Saxofón", "Oboe", "Ukelele", "Fagot"]],
  [1, "Cantantes españoles",
    ["Rosalía", "Alejandro Sanz", "Julio Iglesias", "Enrique Iglesias", "Raphael", "Pablo Alborán", "Aitana", "David Bisbal", "Joaquín Sabina", "Camilo Sesto", "Rocío Jurado", "Lola Flores", "C. Tangana", "Quevedo", "Manuel Carrasco"],
    ["Shakira", "Juanes", "Luis Miguel", "Ricky Martin", "Thalía", "Carlos Vives", "Marc Anthony", "Chayanne", "Karol G", "Gloria Estefan"]],
  [1, "Cantantes latinoamericanos",
    ["Shakira", "Juanes", "Luis Miguel", "Ricky Martin", "Thalía", "Carlos Vives", "Rubén Blades", "Chayanne", "Karol G", "Bad Bunny", "Mercedes Sosa", "Celia Cruz", "Juan Gabriel", "Daddy Yankee", "Maluma"],
    ["Rosalía", "Alejandro Sanz", "Julio Iglesias", "Raphael", "Pablo Alborán", "Aitana", "David Bisbal", "Joaquín Sabina", "Camilo Sesto", "Lola Flores"]],
  [1, "Cantantes con nombre artístico de una sola palabra",
    ["Madonna", "Shakira", "Rihanna", "Adele", "Beyoncé", "Prince", "Sting", "Bono", "Cher", "Rosalía", "Drake", "Eminem", "Björk", "Sia", "Usher"],
    ["Michael Jackson", "Elvis Presley", "Taylor Swift", "Ed Sheeran", "Bruno Mars", "Lady Gaga", "Katy Perry", "Bad Bunny", "Ricky Martin", "Billie Eilish"]],

  // ---- Media ----
  [2, "Canciones de The Beatles",
    ["Yesterday", "Let It Be", "Hey Jude", "Help!", "Yellow Submarine", "Come Together", "Something", "Here Comes the Sun", "Penny Lane", "Strawberry Fields Forever", "All You Need Is Love", "Revolution", "Eleanor Rigby", "Love Me Do", "A Hard Day's Night"],
    ["Imagine", "Bohemian Rhapsody", "Satisfaction", "Stairway to Heaven", "Hotel California", "Wonderwall", "My Way", "Thriller", "Smells Like Teen Spirit", "Like a Rolling Stone"]],
  [2, "Canciones de Queen",
    ["Bohemian Rhapsody", "We Will Rock You", "We Are the Champions", "Don't Stop Me Now", "Another One Bites the Dust", "Somebody to Love", "Radio Ga Ga", "I Want to Break Free", "Under Pressure", "Killer Queen", "The Show Must Go On", "Who Wants to Live Forever", "Love of My Life", "Bicycle Race", "A Kind of Magic"],
    ["Hey Jude", "Imagine", "Highway to Hell", "Sweet Child o' Mine", "Livin' on a Prayer", "Billie Jean", "Hotel California", "Purple Rain", "Born to Run", "Smoke on the Water"]],
  [2, "Canciones de Michael Jackson",
    ["Thriller", "Billie Jean", "Beat It", "Smooth Criminal", "Black or White", "Bad", "Man in the Mirror", "Heal the World", "Earth Song", "Don't Stop 'Til You Get Enough", "Rock with You", "Remember the Time", "They Don't Care About Us", "You Are Not Alone", "Dirty Diana"],
    ["Like a Prayer", "Purple Rain", "Vogue", "Uptown Funk", "I Will Always Love You", "Material Girl", "Single Ladies", "Kiss", "Faith", "Careless Whisper"]],
  [2, "Óperas",
    ["La traviata", "Carmen", "Aida", "La flauta mágica", "Las bodas de Fígaro", "Don Giovanni", "Rigoletto", "Tosca", "La bohème", "Madama Butterfly", "Turandot", "El barbero de Sevilla", "Nabucco", "Otello", "Tannhäuser"],
    ["El lago de los cisnes", "El cascanueces", "Las cuatro estaciones", "El Mesías", "Bolero", "El bello Danubio azul", "La consagración de la primavera", "Para Elisa", "Claro de luna", "El Moldava"]],
  [2, "Instrumentos de una orquesta sinfónica",
    ["Violín", "Viola", "Violonchelo", "Contrabajo", "Flauta", "Oboe", "Clarinete", "Fagot", "Trompa", "Trompeta", "Trombón", "Tuba", "Timbal", "Arpa", "Flautín"],
    ["Guitarra eléctrica", "Bajo eléctrico", "Batería", "Gaita", "Ukelele", "Banjo", "Sitar", "Charango", "Bandurria", "Didgeridoo"]],
  [2, "Ganadores de Eurovisión",
    ["ABBA", "Céline Dion", "Måneskin", "Loreen", "Conchita Wurst", "Lordi", "Netta", "Salvador Sobral", "Kalush Orchestra", "Johnny Logan", "Massiel", "Salomé", "Duncan Laurence", "Nemo", "Alexander Rybak"],
    ["Chanel", "Blanca Paloma", "Rosa López", "Raphael", "Mocedades", "Julio Iglesias", "Ruth Lorenzo", "Edurne", "Manel Navarro", "Barei"]],
  [2, "Raperos",
    ["Eminem", "Jay-Z", "Kanye West", "Drake", "Kendrick Lamar", "Snoop Dogg", "Tupac", "Notorious B.I.G.", "50 Cent", "Nicki Minaj", "Travis Scott", "Lil Wayne", "Dr. Dre", "Ice Cube", "Cardi B"],
    ["Adele", "Bruno Mars", "Ed Sheeran", "Lady Gaga", "Coldplay", "Shakira", "Elton John", "Celine Dion", "Bon Jovi", "Lana Del Rey"]],
  [2, "Canciones de Shakira",
    ["Waka Waka", "Hips Don't Lie", "Whenever, Wherever", "La tortura", "Ojos así", "Estoy aquí", "She Wolf", "Chantaje", "La bicicleta", "Loca", "Antología", "Pies descalzos", "Te felicito", "Rabiosa", "Bzrp Music Sessions #53"],
    ["Despacito", "Gasolina", "La Macarena", "Livin' la vida loca", "Bailando", "Corazón partido", "Mi gente", "Felices los 4", "Tusa", "Danza Kuduro"]],
  [2, "Musicales",
    ["El fantasma de la ópera", "Los miserables", "Cats", "Mamma Mia!", "El rey león", "Chicago", "Grease", "Hamilton", "Wicked", "West Side Story", "Cabaret", "Evita", "Hair", "Jesucristo Superstar", "Sonrisas y lágrimas"],
    ["Carmen", "La traviata", "El lago de los cisnes", "El cascanueces", "Aida", "Tosca", "Giselle", "Don Giovanni", "Turandot", "Rigoletto"]],
  [2, "Canciones de ABBA",
    ["Dancing Queen", "Mamma Mia", "Waterloo", "Fernando", "The Winner Takes It All", "Gimme! Gimme! Gimme!", "Super Trouper", "Take a Chance on Me", "Money, Money, Money", "SOS", "Chiquitita", "Voulez-Vous", "Knowing Me, Knowing You", "I Have a Dream", "Thank You for the Music"],
    ["Bohemian Rhapsody", "Like a Virgin", "I Will Survive", "YMCA", "Stayin' Alive", "Girls Just Want to Have Fun", "Heart of Glass", "Hotel California", "Africa", "Take On Me"]],

  // ---- Difícil ----
  [3, "Óperas de Giuseppe Verdi",
    ["La traviata", "Aida", "Rigoletto", "Nabucco", "Otello", "Falstaff", "Il trovatore", "Un ballo in maschera", "La forza del destino", "Don Carlo", "Macbeth", "Ernani", "Simon Boccanegra", "Luisa Miller", "Attila"],
    ["Tosca", "La bohème", "Madama Butterfly", "Turandot", "Carmen", "Lucia di Lammermoor", "Norma", "El barbero de Sevilla", "Don Giovanni", "Cavalleria rusticana"]],
  [3, "Obras de Johann Sebastian Bach",
    ["Conciertos de Brandeburgo", "Pasión según san Mateo", "Pasión según san Juan", "El clave bien temperado", "Variaciones Goldberg", "Partitas para violín", "El arte de la fuga", "Misa en si menor", "Oratorio de Navidad", "Ofrenda musical", "Aria de la Suite n.º 3", "Suites para violonchelo", "Magnificat", "Cantata del café", "Jesús, alegría de los hombres"],
    ["El Mesías", "Música acuática", "Las cuatro estaciones", "Réquiem en re menor", "Para Elisa", "El Danubio azul", "Canon de Pachelbel", "Adagio de Albinoni", "Bolero", "Danza macabra"]],
  [3, "Miembros de Queen o de The Beatles",
    ["Freddie Mercury", "Brian May", "Roger Taylor", "John Deacon", "John Lennon", "Paul McCartney", "George Harrison", "Ringo Starr", "Pete Best", "Stuart Sutcliffe"],
    ["Mick Jagger", "Keith Richards", "Robert Plant", "Jimmy Page", "David Gilmour", "Roger Waters", "Pete Townshend", "Roger Daltrey", "Eric Clapton", "Ozzy Osbourne", "Bono", "The Edge", "Kurt Cobain", "Dave Grohl", "Sting"]],
  [3, "Compositores españoles",
    ["Manuel de Falla", "Isaac Albéniz", "Enrique Granados", "Joaquín Rodrigo", "Pablo Sarasate", "Tomás Luis de Victoria", "Joaquín Turina", "Federico Chueca", "Tomás Bretón", "Ruperto Chapí", "Francisco Tárrega", "Antonio Soler", "Juan Crisóstomo Arriaga", "Xavier Montsalvatge", "Cristóbal de Morales"],
    ["Astor Piazzolla", "Heitor Villa-Lobos", "Alberto Ginastera", "Carlos Chávez", "Agustín Lara", "Ernesto Lecuona", "Domenico Scarlatti", "Maurice Ravel", "Georges Bizet", "Luigi Boccherini"]],
  [3, "Términos de tempo musical",
    ["Allegro", "Adagio", "Andante", "Presto", "Largo", "Lento", "Moderato", "Vivace", "Allegretto", "Andantino", "Prestissimo", "Grave", "Larghetto", "Accelerando", "Ritardando"],
    ["Forte", "Piano", "Fortissimo", "Pianissimo", "Crescendo", "Diminuendo", "Staccato", "Legato", "Pizzicato", "Sforzando"]],
  [3, "Discos de Pink Floyd",
    ["The Dark Side of the Moon", "The Wall", "Wish You Were Here", "Animals", "Meddle", "Atom Heart Mother", "The Piper at the Gates of Dawn", "A Saucerful of Secrets", "Ummagumma", "Obscured by Clouds", "The Final Cut", "A Momentary Lapse of Reason", "The Division Bell", "The Endless River", "More"],
    ["Abbey Road", "Led Zeppelin IV", "A Night at the Opera", "Thriller", "Nevermind", "Rumours", "OK Computer", "Back in Black", "Sgt. Pepper's", "Hotel California"]],
  [3, "Ballets",
    ["El lago de los cisnes", "El cascanueces", "La bella durmiente", "Giselle", "Coppélia", "El pájaro de fuego", "Petrushka", "La consagración de la primavera", "Romeo y Julieta", "Don Quijote", "La Bayadera", "Espartaco", "El amor brujo", "El sombrero de tres picos", "Cenicienta"],
    ["La traviata", "Rigoletto", "Aida", "Tosca", "Las cuatro estaciones", "El Mesías", "La flauta mágica", "Nabucco", "Fidelio", "Turandot"]],
  [3, "Grupos de la Movida madrileña",
    ["Alaska y los Pegamoides", "Radio Futura", "Nacha Pop", "Los Secretos", "Ejecutivos Agresivos", "Burning", "Gabinete Caligari", "Kaka de Luxe", "Parálisis Permanente", "Los Zombies", "Aviador Dro", "Los Elegantes", "Glutamato Ye-Yé", "Los Pistones", "Derribos Arias"],
    ["Héroes del Silencio", "Estopa", "El Canto del Loco", "Extremoduro", "Jarabe de Palo", "La Oreja de Van Gogh", "Amaral", "Fito & Fitipaldis", "Vetusta Morla", "Love of Lesbian"]],
  [3, "Sinfonías con sobrenombre",
    ["Heroica", "Pastoral", "Coral", "Inacabada", "Del Nuevo Mundo", "Patética", "Júpiter", "Fantástica", "Titán", "Resurrección", "Escocesa", "Italiana", "Leningrado", "La sorpresa", "Los adioses"],
    ["Claro de luna", "Para Elisa", "Bolero", "Las cuatro estaciones", "El Mesías", "Carmina Burana", "Pedro y el lobo", "Danza húngara", "Rapsodia en azul", "El Moldava"]],
  [3, "Cantantes de ópera",
    ["Luciano Pavarotti", "Plácido Domingo", "José Carreras", "Maria Callas", "Montserrat Caballé", "Teresa Berganza", "Alfredo Kraus", "Enrico Caruso", "Renata Tebaldi", "Joan Sutherland", "Cecilia Bartoli", "Anna Netrebko", "Jonas Kaufmann", "Victoria de los Ángeles", "Juan Diego Flórez"],
    ["Julio Iglesias", "Frank Sinatra", "Nino Bravo", "Raphael", "Camilo Sesto", "Freddie Mercury", "Céline Dion", "Barbra Streisand", "Charles Aznavour", "Édith Piaf"]],
];
