// Campo de minas · Películas y series. [difficulty, prompt, right answers, mines] (see ./index.js).
// Awards that can still be won only use people and titles whose answer can't change any more.
export default [
  // ---- Fácil ----
  [1, "Películas de Disney o Pixar",
    ["El rey león", "Frozen", "Toy Story", "Buscando a Nemo", "La sirenita", "Aladdín", "Coco", "Up", "Blancanieves y los siete enanitos", "La bella y la bestia", "Encanto", "Monstruos S.A.", "Los increíbles", "Del revés", "Vaiana"],
    ["Shrek", "Madagascar", "Kung Fu Panda", "Cómo entrenar a tu dragón", "Hotel Transilvania", "Gru, mi villano favorito", "Space Jam", "Spirit", "La LEGO película", "Minions"]],
  [1, "Superhéroes de Marvel",
    ["Spider-Man", "Iron Man", "Capitán América", "Thor", "Hulk", "Viuda Negra", "Pantera Negra", "Doctor Strange", "Ant-Man", "Lobezno", "Deadpool", "Capitana Marvel", "Ojo de Halcón", "Bruja Escarlata", "Star-Lord"],
    ["Batman", "Superman", "Wonder Woman", "Flash", "Aquaman", "Linterna Verde", "Robin", "Catwoman", "Cyborg", "Shazam"]],
  [1, "Personajes de Star Wars",
    ["Luke Skywalker", "Darth Vader", "Han Solo", "Leia", "Yoda", "Chewbacca", "R2-D2", "C-3PO", "Obi-Wan Kenobi", "Palpatine", "Boba Fett", "Kylo Ren", "Rey", "Jabba el Hutt", "Grogu"],
    ["Spock", "Capitán Kirk", "Gandalf", "Neo", "Harry Potter", "E.T.", "Terminator", "Indiana Jones", "Marty McFly", "Frodo"]],
  [1, "Series (no películas)",
    ["Friends", "Los Simpson", "Breaking Bad", "Juego de Tronos", "Stranger Things", "La casa de papel", "The Office", "Perdidos", "Dexter", "Los Soprano", "The Crown", "Narcos", "Élite", "Merlí", "Black Mirror"],
    ["Titanic", "Avatar", "Gladiator", "Jurassic Park", "Pulp Fiction", "El padrino", "Forrest Gump", "Matrix", "Toy Story", "Volver"]],
  [1, "Personajes de Los Simpson",
    ["Homer", "Marge", "Bart", "Lisa", "Maggie", "Abuelo Simpson", "Ned Flanders", "Señor Burns", "Smithers", "Moe", "Barney", "Krusty", "Milhouse", "Apu", "Jefe Wiggum"],
    ["Peter Griffin", "Stewie", "Stan Smith", "Eric Cartman", "Kenny", "Bob Esponja", "Patricio", "Fry", "Bender", "Rick Sánchez"]],
  [1, "Actores y actrices de Hollywood",
    ["Tom Hanks", "Leonardo DiCaprio", "Brad Pitt", "Tom Cruise", "Meryl Streep", "Julia Roberts", "Johnny Depp", "Will Smith", "Morgan Freeman", "Scarlett Johansson", "Denzel Washington", "Angelina Jolie", "Robert De Niro", "Al Pacino", "Nicole Kidman"],
    ["Christopher Nolan", "James Cameron", "Stanley Kubrick", "Ridley Scott", "Denis Villeneuve", "Hans Zimmer", "John Williams", "Ennio Morricone", "Bong Joon-ho", "Roger Deakins"]],
  [1, "Películas de terror",
    ["El exorcista", "Psicosis", "It", "Scream", "Halloween", "Pesadilla en Elm Street", "Viernes 13", "Expediente Warren", "Saw", "La matanza de Texas", "El resplandor", "Poltergeist", "Insidious", "Paranormal Activity", "The Ring"],
    ["Toy Story", "Mamma Mia!", "Titanic", "Notting Hill", "Shrek", "Forrest Gump", "Mary Poppins", "La La Land", "Grease", "Ratatouille"]],
  [1, "Personajes de Disney",
    ["Mickey Mouse", "Minnie", "Pato Donald", "Goofy", "Pluto", "Simba", "Elsa", "Ariel", "Mulán", "Stitch", "Pocahontas", "Buzz Lightyear", "Woody", "Rapunzel", "Vaiana"],
    ["Bugs Bunny", "Pato Lucas", "Shrek", "Pikachu", "Bob Esponja", "Garfield", "Snoopy", "Scooby-Doo", "Tom y Jerry", "Pantera Rosa"]],
  [1, "Series de dibujos animados",
    ["Los Simpson", "Bob Esponja", "Padre de familia", "South Park", "Futurama", "Doraemon", "Pokémon", "Dragon Ball", "Hora de aventuras", "Rick y Morty", "Peppa Pig", "Shin-chan", "Los Picapiedra", "Scooby-Doo", "Las Supernenas"],
    ["Friends", "Breaking Bad", "Juego de Tronos", "La casa de papel", "Stranger Things", "The Office", "Perdidos", "Narcos", "Dexter", "The Crown"]],
  [1, "Personajes de Shrek",
    ["Shrek", "Asno", "Fiona", "Gato con Botas", "Lord Farquaad", "Dragona", "Hada Madrina", "Príncipe Encantador", "Pinocho", "Jengi", "Rumpelstiltskin", "Rey Harold", "Los tres cerditos", "Lobo feroz", "Doris"],
    ["Simba", "Woody", "Buzz Lightyear", "Nemo", "Elsa", "Olaf", "Stitch", "Mickey Mouse", "Rayo McQueen", "Sulley"]],

  // ---- Media ----
  [2, "Películas dirigidas por Steven Spielberg",
    ["Tiburón", "E.T.", "Jurassic Park", "La lista de Schindler", "Salvar al soldado Ryan", "En busca del arca perdida", "Encuentros en la tercera fase", "Atrápame si puedes", "La terminal", "Minority Report", "Lincoln", "Ready Player One", "West Side Story", "Los Fabelman", "Hook"],
    ["Star Wars", "Titanic", "Avatar", "Pulp Fiction", "El padrino", "Origen", "Alien", "Matrix", "Forrest Gump", "Rocky"]],
  [2, "Ganadoras del Óscar a mejor película",
    ["Titanic", "El padrino", "Forrest Gump", "Gladiator", "El silencio de los corderos", "La lista de Schindler", "Parásitos", "Oppenheimer", "Casablanca", "Ben-Hur", "Rocky", "Una mente maravillosa", "El retorno del rey", "Slumdog Millionaire", "Braveheart"],
    ["Pulp Fiction", "Avatar", "E.T.", "Star Wars", "Ciudadano Kane", "Psicosis", "Tiburón", "Origen", "La La Land", "Regreso al futuro"]],
  [2, "Películas de Pedro Almodóvar",
    ["Todo sobre mi madre", "Hable con ella", "Volver", "Mujeres al borde de un ataque de nervios", "La piel que habito", "Dolor y gloria", "Átame", "Tacones lejanos", "La flor de mi secreto", "Carne trémula", "Los abrazos rotos", "Julieta", "Madres paralelas", "La habitación de al lado", "Kika"],
    ["Mar adentro", "Abre los ojos", "Los otros", "El laberinto del fauno", "Ocho apellidos vascos", "Torrente", "La sociedad de la nieve", "Lo imposible", "El orfanato", "Jamón, jamón"]],
  [2, "Personajes de Friends",
    ["Rachel", "Ross", "Monica", "Chandler", "Joey", "Phoebe", "Gunther", "Janice", "Mike", "Emily", "Carol", "Susan", "Ursula", "Richard", "Frank Jr."],
    ["Sheldon", "Leonard", "Penny", "Raj", "Ted Mosby", "Barney Stinson", "Marshall", "Michael Scott", "Dwight", "Jim Halpert"]],
  [2, "Películas de Christopher Nolan",
    ["Origen", "Interstellar", "El caballero oscuro", "Memento", "El truco final", "Dunkerque", "Tenet", "Oppenheimer", "Batman Begins", "La leyenda renace", "Insomnio", "Following"],
    ["Matrix", "Avatar", "Gravity", "Blade Runner", "Alien", "Titanic", "Gladiator", "Pulp Fiction", "Seven", "El club de la lucha", "Shutter Island", "Joker", "Dune"]],
  [2, "Series españolas",
    ["La casa de papel", "Élite", "Aquí no hay quien viva", "Los Serrano", "Cuéntame cómo pasó", "Médico de familia", "El Ministerio del Tiempo", "Vis a vis", "Las chicas del cable", "Merlí", "Física o Química", "Velvet", "El internado", "Gran Hotel", "Paquita Salas"],
    ["Narcos", "Dark", "Lupin", "El juego del calamar", "Breaking Bad", "Friends", "Sherlock", "The Crown", "Gomorra", "Betty, la fea"]],
  [2, "Villanos del cine",
    ["Darth Vader", "Joker", "Hannibal Lecter", "Voldemort", "Thanos", "Freddy Krueger", "Scar", "Úrsula", "Cruella de Vil", "Sauron", "Norman Bates", "Jafar", "Hans Landa", "Agente Smith", "Pennywise"],
    ["Luke Skywalker", "Indiana Jones", "Forrest Gump", "Simba", "Harry Potter", "Frodo", "Neo", "Rocky Balboa", "Woody", "Ellen Ripley"]],
  [2, "Películas de animación japonesa",
    ["El viaje de Chihiro", "Mi vecino Totoro", "La princesa Mononoke", "El castillo ambulante", "Akira", "Your Name", "Ponyo", "Nicky, la aprendiz de bruja", "La tumba de las luciérnagas", "El niño y la garza", "Perfect Blue", "Suzume", "Porco Rosso", "Paprika", "El castillo en el cielo"],
    ["Coco", "Shrek", "Frozen", "Toy Story", "Up", "Ratatouille", "Klaus", "Kung Fu Panda", "Big Hero 6", "Pesadilla antes de Navidad"]],
  [2, "Películas dirigidas por Quentin Tarantino",
    ["Pulp Fiction", "Reservoir Dogs", "Kill Bill: Volumen 1", "Kill Bill: Volumen 2", "Malditos bastardos", "Django desencadenado", "Los odiosos ocho", "Érase una vez en Hollywood", "Jackie Brown", "Death Proof"],
    ["Abierto hasta el amanecer", "Amor a quemarropa", "Asesinos natos", "El club de la lucha", "Seven", "Uno de los nuestros", "Snatch", "Fargo", "El gran Lebowski", "Drive", "Trainspotting", "Scarface", "Casino", "Taxi Driver", "Lock & Stock"]],
  [2, "Directores de cine",
    ["Spielberg", "Tarantino", "Almodóvar", "Kubrick", "Hitchcock", "Scorsese", "Nolan", "Coppola", "Kurosawa", "Fellini", "Buñuel", "Amenábar", "Tim Burton", "Guillermo del Toro", "James Cameron"],
    ["Meryl Streep", "Leonardo DiCaprio", "Julia Roberts", "Will Smith", "Nicole Kidman", "Hans Zimmer", "John Williams", "Marilyn Monroe", "Audrey Hepburn", "Brad Pitt"]],

  // ---- Difícil ----
  [3, "Actores que han interpretado a James Bond",
    ["Sean Connery", "Roger Moore", "Pierce Brosnan", "Daniel Craig", "Timothy Dalton", "George Lazenby", "David Niven", "Barry Nelson"],
    ["Christopher Lee", "Javier Bardem", "Mads Mikkelsen", "Gert Fröbe", "Rami Malek", "Christoph Waltz", "Ralph Fiennes", "Judi Dench", "Ben Whishaw", "Mel Gibson", "Tom Cruise", "Matt Damon", "Clive Owen", "Sean Bean", "Desmond Llewelyn", "Telly Savalas", "Jonathan Pryce"]],
  [3, "Ganadores del Óscar como actor o actriz protagonista",
    ["Daniel Day-Lewis", "Tom Hanks", "Anthony Hopkins", "Leonardo DiCaprio", "Joaquin Phoenix", "Meryl Streep", "Jack Nicholson", "Kate Winslet", "Natalie Portman", "Julia Roberts", "Charlize Theron", "Emma Stone", "Nicole Kidman", "Russell Crowe", "Cate Blanchett"],
    ["Richard Burton", "Marilyn Monroe", "James Dean", "Steve McQueen", "Alan Rickman", "Natalie Wood", "Montgomery Clift", "Rita Hayworth", "Bruce Lee", "Christopher Reeve"]],
  [3, "Películas de Alfred Hitchcock",
    ["Psicosis", "Los pájaros", "Vértigo", "La ventana indiscreta", "Con la muerte en los talones", "Rebeca", "Crimen perfecto", "Recuerda", "Encadenados", "La soga", "Extraños en un tren", "Marnie, la ladrona", "Atrapa a un ladrón", "Frenesí", "39 escalones"],
    ["El tercer hombre", "Ciudadano Kane", "Casablanca", "El halcón maltés", "Laura", "Perdición", "Sed de mal", "Charada", "Luz que agoniza", "Las diabólicas"]],
  [3, "Ganadores del Óscar a mejor dirección",
    ["Spielberg", "Scorsese", "Coppola", "Clint Eastwood", "Kathryn Bigelow", "Alfonso Cuarón", "Iñárritu", "Guillermo del Toro", "Bong Joon-ho", "Christopher Nolan", "James Cameron", "Peter Jackson", "Ang Lee", "Chloé Zhao", "Damien Chazelle"],
    ["Stanley Kubrick", "Alfred Hitchcock", "Orson Welles", "Sergio Leone", "Akira Kurosawa", "Ingmar Bergman", "Federico Fellini", "Robert Altman", "Luis Buñuel", "David Lynch"]],
  [3, "Ganadoras del Goya a mejor película",
    ["Mar adentro", "Todo sobre mi madre", "Los otros", "Celda 211", "Pa negre", "Volver", "La sociedad de la nieve", "As bestas", "El buen patrón", "Campeones", "Truman", "La isla mínima", "Blancanieves", "Tesis", "Belle Époque"],
    ["El laberinto del fauno", "Ocho apellidos vascos", "Lo imposible", "El orfanato", "Torrente", "Abre los ojos", "Jamón, jamón", "Rec", "El día de la bestia", "Airbag"]],
  [3, "Series de HBO",
    ["Los Soprano", "The Wire", "Juego de Tronos", "Succession", "The Last of Us", "Chernobyl", "True Detective", "A dos metros bajo tierra", "Sexo en Nueva York", "Westworld", "Euphoria", "Boardwalk Empire", "Veep", "Big Little Lies", "The White Lotus"],
    ["Breaking Bad", "Mad Men", "Stranger Things", "The Crown", "House of Cards", "Perdidos", "Friends", "Los Simpson", "The Mandalorian", "The Boys"]],
  [3, "Personajes de Juego de Tronos",
    ["Jon Nieve", "Daenerys", "Tyrion", "Cersei", "Jaime Lannister", "Arya", "Sansa", "Ned Stark", "Bran", "Joffrey", "Theon", "Brienne", "Meñique", "Varys", "El Perro"],
    ["Geralt de Rivia", "Aragorn", "Legolas", "Ragnar Lothbrok", "Uhtred", "Merlín", "Rand al'Thor", "Kvothe", "Elric", "Conan"]],
  [3, "Películas de Stanley Kubrick",
    ["2001: una odisea del espacio", "La naranja mecánica", "El resplandor", "La chaqueta metálica", "Espartaco", "Barry Lyndon", "Lolita", "¿Teléfono rojo? Volamos hacia Moscú", "Senderos de gloria", "Eyes Wide Shut", "Atraco perfecto", "El beso del asesino", "Miedo y deseo"],
    ["A.I. Inteligencia Artificial", "Blade Runner", "Alien", "Apocalypse Now", "Taxi Driver", "Encuentros en la tercera fase", "Solaris", "El exorcista", "Platoon", "Interstellar", "Matrix", "Origen"]],
  [3, "Películas de Studio Ghibli",
    ["El viaje de Chihiro", "Mi vecino Totoro", "La princesa Mononoke", "El castillo ambulante", "Ponyo", "Nicky, la aprendiz de bruja", "La tumba de las luciérnagas", "El niño y la garza", "Porco Rosso", "El castillo en el cielo", "El cuento de la princesa Kaguya", "Susurros del corazón", "Pompoko", "El viento se levanta", "Arrietty"],
    ["Akira", "Your Name", "Perfect Blue", "Paprika", "Suzume", "Ghost in the Shell", "Summer Wars", "El chico y la bestia", "Mirai", "A Silent Voice"]],
  [3, "Personajes de Breaking Bad",
    ["Walter White", "Jesse Pinkman", "Skyler", "Hank", "Marie", "Walter Jr.", "Saul Goodman", "Gus Fring", "Mike Ehrmantraut", "Tuco", "Todd", "Lydia", "Gale", "Jane", "Héctor Salamanca"],
    ["Tony Soprano", "Don Draper", "Michael Scofield", "Dexter Morgan", "Tommy Shelby", "Pablo Escobar", "Rust Cohle", "Omar Little", "Nucky Thompson", "Jax Teller"]],
];
