// Campo de minas · Videojuegos. [difficulty, prompt, right answers, mines] (see ./index.js).
export default [
  // ---- Fácil ----
  [1, "Personajes de Nintendo",
    ["Mario", "Luigi", "Peach", "Bowser", "Yoshi", "Donkey Kong", "Link", "Zelda", "Pikachu", "Kirby", "Samus", "Wario", "Toad", "Fox McCloud", "Ganondorf"],
    ["Sonic", "Crash Bandicoot", "Spyro", "Lara Croft", "Master Chief", "Kratos", "Pac-Man", "Mega Man", "Solid Snake", "Ezio Auditore"]],
  [1, "Pokémon",
    ["Pikachu", "Charmander", "Bulbasaur", "Squirtle", "Jigglypuff", "Meowth", "Psyduck", "Snorlax", "Mewtwo", "Eevee", "Gengar", "Lucario", "Gyarados", "Onix", "Magikarp"],
    ["Agumon", "Gabumon", "Patamon", "Garurumon", "Totoro", "Stitch", "Yoshi", "Kirby", "Sonic", "Doraemon"]],
  [1, "Consolas de videojuegos",
    ["PlayStation", "Xbox", "Nintendo Switch", "Wii", "Game Boy", "Nintendo 64", "Mega Drive", "Dreamcast", "GameCube", "Nintendo DS", "PSP", "Atari 2600", "Super Nintendo", "Game Boy Advance", "PS Vita"],
    ["iPhone", "Kindle", "Walkman", "iPod", "Discman", "Chromecast", "Apple Watch", "Roomba", "Alexa", "MacBook"]],
  [1, "Juegos de la saga Mario",
    ["Super Mario Bros.", "Mario Kart", "Super Mario 64", "Mario Party", "Super Mario Galaxy", "Super Mario Odyssey", "Paper Mario", "Mario Tennis", "Super Mario Sunshine", "Super Mario World", "Dr. Mario", "Mario Golf", "Super Mario Maker", "Mario & Luigi", "Super Mario Wonder"],
    ["Sonic the Hedgehog", "Crash Bandicoot", "Tetris", "Minecraft", "Fortnite", "The Legend of Zelda", "Halo", "Pac-Man", "Street Fighter", "Metroid"]],
  [1, "Personajes que nacieron en un videojuego",
    ["Mario", "Sonic", "Pac-Man", "Lara Croft", "Link", "Kratos", "Master Chief", "Pikachu", "Crash Bandicoot", "Kirby", "Steve de Minecraft", "Donkey Kong", "Mega Man", "Spyro", "Ezio Auditore"],
    ["Shrek", "Mickey Mouse", "Bob Esponja", "Harry Potter", "Batman", "Spider-Man", "Homer Simpson", "Darth Vader", "Goku", "Garfield"]],
  [1, "Juegos que nacieron para el móvil",
    ["Candy Crush", "Angry Birds", "Clash Royale", "Clash of Clans", "Pokémon GO", "Subway Surfers", "Temple Run", "Flappy Bird", "Fruit Ninja", "Cut the Rope", "Brawl Stars", "Monument Valley", "Doodle Jump", "Hay Day", "Royal Match"],
    ["The Last of Us", "Gears of War", "Ghost of Tsushima", "Red Dead Redemption 2", "The Witcher 3", "Gran Turismo 7", "Horizon Zero Dawn", "Bloodborne", "Starfield", "Metroid Prime"]],
  [1, "Géneros de videojuegos",
    ["Plataformas", "Shooter", "RPG", "Estrategia", "Carreras", "Lucha", "Simulación", "Aventura gráfica", "Puzle", "Battle royale", "MMORPG", "Sandbox", "Survival horror", "Metroidvania", "Roguelike"],
    ["Comedia romántica", "Telenovela", "Documental", "Soneto", "Haiku", "Sinfonía", "Bolero", "Tango", "Ensayo", "Fábula"]],
  [1, "Personajes de Super Mario",
    ["Mario", "Luigi", "Peach", "Bowser", "Yoshi", "Toad", "Wario", "Waluigi", "Daisy", "Estela", "Bowser Jr.", "Boo", "Goomba", "Koopa Troopa", "Kamek"],
    ["Link", "Zelda", "Kirby", "Samus", "Pikachu", "Fox McCloud", "Ness", "Captain Falcon", "Sonic", "Tails"]],
  [1, "Cosas de Minecraft",
    ["Creeper", "Enderman", "Aldeano", "Steve", "Ender Dragon", "Wither", "Redstone", "Nether", "Netherita", "Mesa de trabajo", "Obsidiana", "Ghast", "Piglin", "Blaze", "Shulker"],
    ["Goomba", "Chocobo", "Moguri", "Pokéball", "Trifuerza", "Rupia", "Estrella de poder", "Anillo de Sonic", "Esmeralda del Caos", "Blinky"]],
  [1, "Juegos de lucha",
    ["Street Fighter", "Mortal Kombat", "Tekken", "Super Smash Bros.", "Dragon Ball FighterZ", "Soulcalibur", "The King of Fighters", "Dead or Alive", "Virtua Fighter", "Guilty Gear", "Injustice", "BlazBlue", "Killer Instinct", "Bloody Roar", "Marvel vs. Capcom"],
    ["Tetris", "Minecraft", "Mario Kart", "Los Sims", "Candy Crush", "FIFA", "Animal Crossing", "Gran Turismo", "Pac-Man", "Portal"]],

  // ---- Media ----
  [2, "Videojuegos de deportes",
    ["FIFA", "Pro Evolution Soccer", "NBA 2K", "Madden NFL", "Rocket League", "Wii Sports", "Tony Hawk's Pro Skater", "Mario Tennis", "Top Spin", "NHL", "MLB The Show", "Football Manager", "PGA Tour", "Punch-Out!!", "Fight Night"],
    ["Minecraft", "Tetris", "Pokémon", "Zelda", "Halo", "Call of Duty", "Los Sims", "Candy Crush", "Among Us", "Resident Evil"]],
  [2, "Juegos de Pokémon",
    ["Pokémon Rojo y Azul", "Pokémon Oro y Plata", "Pokémon Rubí y Zafiro", "Pokémon Diamante y Perla", "Pokémon Blanco y Negro", "Pokémon X e Y", "Pokémon Sol y Luna", "Pokémon Espada y Escudo", "Pokémon Escarlata y Púrpura", "Pokémon GO", "Pokémon Snap", "Pokémon Stadium", "Leyendas Pokémon: Arceus", "Pokémon Amarillo", "Pokémon Esmeralda"],
    ["Digimon World", "Yo-kai Watch", "Monster Hunter", "Palworld", "Temtem", "Dragon Quest Monsters", "Ni no Kuni", "Spyro", "Kirby Star Allies", "Animal Crossing"]],
  [2, "Personajes de The Legend of Zelda",
    ["Link", "Zelda", "Ganondorf", "Navi", "Epona", "Impa", "Midna", "Tingle", "Skull Kid", "Sheik", "Darunia", "Ruto", "Saria", "Revali", "Mipha"],
    ["Samus", "Kirby", "Fox McCloud", "Ness", "Marth", "Cloud", "Sora", "Ryu", "Crono", "Olimar"]],
  [2, "Personajes de Final Fantasy",
    ["Cloud", "Sephiroth", "Tifa", "Aerith", "Squall", "Tidus", "Yuna", "Lightning", "Noctis", "Zidane", "Vivi", "Cid", "Barret", "Auron", "Kefka"],
    ["Sora", "Riku", "Crono", "Link", "Geralt", "Kratos", "Dante", "Solid Snake", "Master Chief", "Ezio Auditore"]],
  [2, "Juegos de Rockstar Games",
    ["GTA V", "GTA San Andreas", "GTA Vice City", "GTA IV", "GTA III", "Red Dead Redemption", "Red Dead Redemption 2", "Max Payne 3", "Bully", "L.A. Noire", "Manhunt", "Midnight Club", "The Warriors", "Rockstar Table Tennis", "Red Dead Revolver"],
    ["Saints Row", "Mafia", "Watch Dogs", "Sleeping Dogs", "Assassin's Creed", "Far Cry", "Cyberpunk 2077", "Just Cause", "The Witcher 3", "Call of Duty"]],
  [2, "Juegos de Valve",
    ["Half-Life", "Half-Life 2", "Half-Life: Alyx", "Portal", "Portal 2", "Counter-Strike", "Counter-Strike 2", "Left 4 Dead", "Left 4 Dead 2", "Dota 2", "Team Fortress 2", "Day of Defeat", "Artifact", "Alien Swarm", "Ricochet"],
    ["Overwatch", "Fortnite", "League of Legends", "Valorant", "Apex Legends", "PUBG", "Rainbow Six Siege", "Doom", "Quake", "BioShock"]],
  [2, "Juegos independientes",
    ["Hollow Knight", "Celeste", "Undertale", "Stardew Valley", "Hades", "Cuphead", "Terraria", "Limbo", "Inside", "Shovel Knight", "Braid", "Dead Cells", "Among Us", "Fez", "Papers, Please"],
    ["Call of Duty", "FIFA", "Assassin's Creed", "Halo", "Gran Turismo", "The Last of Us", "God of War", "Uncharted", "Forza Horizon", "Battlefield"]],
  [2, "Personajes de Street Fighter",
    ["Ryu", "Ken", "Chun-Li", "Guile", "Blanka", "Zangief", "Dhalsim", "E. Honda", "M. Bison", "Vega", "Sagat", "Balrog", "Cammy", "Akuma", "Juri"],
    ["Scorpion", "Sub-Zero", "Liu Kang", "Raiden", "Sonya Blade", "Kazuya", "Jin Kazama", "Heihachi", "Kyo Kusanagi", "Paul Phoenix"]],
  [2, "Juegos de la saga The Legend of Zelda",
    ["Ocarina of Time", "Majora's Mask", "Breath of the Wild", "Tears of the Kingdom", "Twilight Princess", "The Wind Waker", "A Link to the Past", "Skyward Sword", "Link's Awakening", "The Minish Cap", "Spirit Tracks", "Phantom Hourglass", "A Link Between Worlds", "Echoes of Wisdom", "Four Swords"],
    ["Super Metroid", "Okami", "Kid Icarus", "Darksiders", "Star Fox", "Metroid Dread", "Fire Emblem", "Xenoblade", "Kirby's Dream Land", "Golden Sun"]],
  [2, "Compañías de videojuegos",
    ["Nintendo", "Sega", "Capcom", "Konami", "Ubisoft", "Electronic Arts", "Square Enix", "Bandai Namco", "Activision", "Blizzard", "Bethesda", "Rockstar", "Epic Games", "Valve", "CD Projekt"],
    ["Pixar", "Pfizer", "Zara", "Mercadona", "Toyota", "Coca-Cola", "Ikea", "Telefónica", "Rolex", "Ferrari"]],

  // ---- Difícil ----
  [3, "Juego del año en The Game Awards",
    ["Dragon Age: Inquisition", "The Witcher 3", "Overwatch", "Breath of the Wild", "God of War", "Sekiro", "The Last of Us Part II", "It Takes Two", "Elden Ring", "Baldur's Gate 3", "Astro Bot"],
    ["Red Dead Redemption 2", "Hades", "Ghost of Tsushima", "Death Stranding", "Super Mario Odyssey", "Horizon Zero Dawn", "Uncharted 4", "Bloodborne", "Fallout 4", "Metroid Dread", "Tears of the Kingdom", "Black Myth: Wukong", "Final Fantasy VII Rebirth", "Spider-Man 2"]],
  [3, "Juegos de FromSoftware",
    ["Dark Souls", "Dark Souls II", "Dark Souls III", "Demon's Souls", "Bloodborne", "Sekiro", "Elden Ring", "Elden Ring Nightreign", "Armored Core VI", "King's Field", "Déraciné", "Otogi", "Shadow Tower", "Metal Wolf Chaos"],
    ["Lies of P", "Nioh", "Lords of the Fallen", "The Surge", "Hollow Knight", "Salt and Sanctuary", "Remnant", "Mortal Shell", "Wo Long", "Code Vein", "Black Myth: Wukong"]],
  [3, "Personajes de Metal Gear Solid",
    ["Solid Snake", "Big Boss", "Revolver Ocelot", "Otacon", "Liquid Snake", "Raiden", "Meryl", "Gray Fox", "The Boss", "EVA", "Psycho Mantis", "Sniper Wolf", "Kazuhira Miller", "Quiet", "Vamp"],
    ["Sam Fisher", "Agente 47", "Marcus Fenix", "Nathan Drake", "Joel", "Leon S. Kennedy", "Chris Redfield", "Gordon Freeman", "Max Payne", "Arthur Morgan"]],
  [3, "Personajes de Resident Evil",
    ["Leon S. Kennedy", "Chris Redfield", "Jill Valentine", "Claire Redfield", "Albert Wesker", "Ada Wong", "Némesis", "Ethan Winters", "Rebecca Chambers", "Barry Burton", "Lady Dimitrescu", "Ashley Graham", "Sheva Alomar", "Carlos Oliveira", "Mr. X"],
    ["Solid Snake", "Sam Fisher", "Isaac Clarke", "Alan Wake", "James Sunderland", "Pyramid Head", "Joel", "Ellie", "Marcus Fenix", "Doomguy"]],
  [3, "Videojuegos hechos en España",
    ["Blasphemous", "Blasphemous 2", "Gris", "Castlevania: Lords of Shadow", "Metroid Dread", "Commandos", "La Abadía del Crimen", "Rime", "Unepic", "Moonlighter", "Crossing Souls", "Praetorians", "Narita Boy"],
    ["Hollow Knight", "Celeste", "Cuphead", "Dead Cells", "Hades", "Inside", "Limbo", "Ori and the Blind Forest", "Stardew Valley", "Undertale", "Hyper Light Drifter", "Hotline Miami"]],
  [3, "Mapas de Counter-Strike",
    ["Dust II", "Inferno", "Mirage", "Nuke", "Train", "Overpass", "Vertigo", "Ancient", "Anubis", "Cache", "Office", "Italy", "Aztec", "Cobblestone", "Assault"],
    ["Erangel", "Bind", "Haven", "Ascent", "Kings Canyon", "Verdansk", "Tilted Towers", "Summoner's Rift", "Nuketown", "Blood Gulch"]],
  [3, "Campeones de League of Legends",
    ["Ahri", "Yasuo", "Lux", "Jinx", "Teemo", "Garen", "Darius", "Ezreal", "Thresh", "Lee Sin", "Zed", "Katarina", "Vi", "Caitlyn", "Ashe"],
    ["Invoker", "Pudge", "Tracer", "Genji", "Jett", "Reyna", "Wraith", "Kerrigan", "Arthas", "Illidan"]],
  [3, "Juegos de Blizzard",
    ["World of Warcraft", "StarCraft", "StarCraft II", "Diablo", "Diablo II", "Diablo IV", "Diablo Immortal", "Overwatch", "Overwatch 2", "Hearthstone", "Heroes of the Storm", "Warcraft II", "Warcraft III", "The Lost Vikings", "Rock n' Roll Racing"],
    ["League of Legends", "Dota 2", "Age of Empires", "Command & Conquer", "Fortnite", "Valorant", "Guild Wars", "EverQuest", "Final Fantasy XIV", "Apex Legends"]],
  [3, "Creadores de videojuegos",
    ["Shigeru Miyamoto", "Hideo Kojima", "Satoru Iwata", "Hidetaka Miyazaki", "John Carmack", "John Romero", "Sid Meier", "Will Wright", "Gabe Newell", "Peter Molyneux", "Yu Suzuki", "Tim Schafer", "Ron Gilbert", "Markus Persson", "Toby Fox"],
    ["Sergey Brin", "Walt Disney", "Stan Lee", "Hayao Miyazaki", "Tim Berners-Lee", "Mark Zuckerberg", "Jeff Bezos", "Linus Torvalds", "Larry Page", "Warren Buffett"]],
  [3, "Juegos desarrollados por Bethesda",
    ["Skyrim", "Oblivion", "Morrowind", "Daggerfall", "The Elder Scrolls: Arena", "Battlespire", "Redguard", "Fallout 3", "Fallout 4", "Fallout 76", "Starfield", "Fallout Shelter"],
    ["Fallout: New Vegas", "Fallout 2", "The Witcher 3", "Dragon Age", "Mass Effect", "Baldur's Gate 3", "Cyberpunk 2077", "Elden Ring", "Kingdom Come: Deliverance", "Dragon's Dogma", "Gothic", "Two Worlds", "Avowed"]],
];
